{
  "hash": "7895d18907ef7c1aff46b8a30935877d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 2: Spatial Analysis and Visualization\"\nsubtitle: \"Healthcare Access and Equity in Pennsylvania\"\nauthor: \"Parker Otto\"\ndate: today\nformat: \n  html:\n    code-fold: false\n    toc: true\n    toc-location: left\n    theme: darkly\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n\n## Assignment Overview\n\n**Learning Objectives:**\n- Apply spatial operations to answer policy-relevant research questions\n- Integrate census demographic data with spatial analysis\n- Create publication-quality visualizations and maps\n- Work with spatial data from multiple sources\n- Communicate findings effectively for policy audiences\n\n---\n\n## Part 1: Healthcare Access for Vulnerable Populations\n\n### Research Question\n\n**Which Pennsylvania counties have the highest proportion of vulnerable populations (elderly + low-income) living far from hospitals?**\n\nYour analysis should identify counties that should be priorities for healthcare investment and policy intervention.\n\n### Required Analysis Steps\n\nComplete the following analysis, documenting each step with code and brief explanations:\n\n#### Step 1: Data Collection (5 points)\n\nLoad the required spatial data:\n- Pennsylvania county boundaries\n- Pennsylvania hospitals (from lecture data)\n- Pennsylvania census tracts\n\n**Your Task:**\n\n::: {.cell}\n\n:::\n\n\n**Questions to answer:**\n- How many hospitals are in your dataset?\n\n223.\n\n- How many census tracts?\n\n3,445\n\n- What coordinate reference system is each dataset in?\n\nPseudo-Mercator (EPSG 3857)\n\n---\n\n#### Step 2: Get Demographic Data \n\nUse `tidycensus` to download tract-level demographic data for Pennsylvania.\n\n**Required variables:**\n- Total population\n- Median household income\n- Population 65 years and over (you may need to sum multiple age categories)\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get demographic data from ACS\n\nover_65 <- c(\n  \"F_65_66\" = \"B01001_020\", \"F_67_69\" = \"B01001_021\",\n  \"F_70_74\" = \"B01001_022\", \"F_75_79\" = \"B01001_023\",\n  \"F_80_84\" = \"B01001_024\", \"F_85plus\" = \"B01001_025\",\n  \"M_65_66\" = \"B01001_044\", \"M_67_69\" = \"B01001_045\",\n  \"M_70_74\" = \"B01001_046\", \"M_75_79\" = \"B01001_047\",\n  \"M_80_84\" = \"B01001_048\", \"M_85plus\" = \"B01001_049\"\n)\n\nelderly <- get_acs(\n  geography = \"tract\",\n  variables = over_65,\n  state = \"PA\",\n  year = 2022,\n  output = \"wide\"\n)\n\nsum_elderly <- elderly %>%\n  select(-NAME) %>%\n  rowwise() %>%\n  mutate(\n    over_65E = sum(c_across(ends_with(\"E\")), na.rm = TRUE),\n    over_65M = moe_sum(\n      moe = c_across(ends_with(\"M\")),\n      estimate = c_across(ends_with(\"E\")),\n      na.rm = TRUE\n    )\n  ) %>%\n  ungroup() %>% \n  select(\n    GEOID, \n    over_65E, \n    over_65M\n  )\n\ntract_inc <- get_acs(\n  geography = \"tract\",\n  variables = \"B19013_001\",\n  state = \"PA\",\n  year = 2022,\n  output = \"wide\"\n)\n\n?get_acs\n\ntract_data <- get_acs(\n  geography = \"tract\",\n  variables = c(\n    total_pop = \"B01003_001\",\n    median_income = \"B19013_001\"\n  ),\n  state = \"PA\",\n  year = 2022,\n  output = \"wide\"\n  ) %>% \n  left_join(\n    ., \n    sum_elderly,\n    by = \"GEOID\"\n  )\n\n# Join to tract boundaries\n\ntract_data_spat <- pa_tracts %>% \n  left_join(\n    tract_data,\n    by = \"GEOID\"\n  ) %>% \n  select(\n    \"GEOID\",\n    \"NAMELSAD\",\n    \"NAMELSADCO\",\n    \"ALAND\",\n    \"total_popE\",\n    \"total_popM\",\n    \"median_incomeE\",\n    \"median_incomeM\",\n    \"over_65E\",\n    \"over_65M\",\n    \"geometry\"\n  )\n\nsummary(tract_data_spat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    GEOID             NAMELSAD          NAMELSADCO            ALAND          \n Length:3445        Length:3445        Length:3445        Min.   :7.224e+04  \n Class :character   Class :character   Class :character   1st Qu.:1.320e+06  \n Mode  :character   Mode  :character   Mode  :character   Median :4.182e+06  \n                                                          Mean   :3.364e+07  \n                                                          3rd Qu.:2.858e+07  \n                                                          Max.   :1.024e+09  \n                                                                             \n   total_popE      total_popM   median_incomeE   median_incomeM  \n Min.   :    0   Min.   :   4   Min.   : 11558   Min.   :   618  \n 1st Qu.: 2622   1st Qu.: 247   1st Qu.: 55924   1st Qu.:  8867  \n Median : 3669   Median : 374   Median : 70188   Median : 13027  \n Mean   : 3770   Mean   : 403   Mean   : 77527   Mean   : 15437  \n 3rd Qu.: 4803   3rd Qu.: 533   3rd Qu.: 93286   3rd Qu.: 19030  \n Max.   :10323   Max.   :2027   Max.   :250001   Max.   :165570  \n                                NA's   :62       NA's   :69      \n    over_65E         over_65M              geometry   \n Min.   :   0.0   Min.   : 11.0   MULTIPOLYGON :3445  \n 1st Qu.: 424.0   1st Qu.:108.4   epsg:3365    :   0  \n Median : 656.0   Median :154.4   +proj=lcc ...:   0  \n Mean   : 706.6   Mean   :167.9                       \n 3rd Qu.: 927.0   3rd Qu.:215.3                       \n Max.   :2462.0   Max.   :608.2                       \n                                                      \n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- What year of ACS data are you using?\n\n2022\n\n- How many tracts have missing income data?\n\n62.\n\n- What is the median income across all PA census tracts?\n\n$70,188\n\n---\n\n#### Step 3: Define Vulnerable Populations \n\nIdentify census tracts with vulnerable populations based on TWO criteria:\n1. Low median household income (choose an appropriate threshold)\n2. Significant elderly population (choose an appropriate threshold)\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter for vulnerable tracts based on your criteria\n\n#Criteria 1: Median Income Under PA's Living Wage (1 Adult, 0 Children from https://livingwage.mit.edu/states/42)\n\nvuln1 <- 23.32 * (40 * 52)\n\n#If median_incomeE < vuln1, then pop_vuln = VULN\n\n#Criteria 2: Double The Median Population of Elderly Individuals\n\nvuln2 <- 2 * (656 / 3669)\n\n#If over_65E / total_popE > vuln2, then pop_vuln = VULN\n\ntracts_vuln <- tract_data_spat %>% \n  mutate(\n    pop_vuln = ifelse(\n      median_incomeE < vuln1 | (over_65E / total_popE) > vuln2,\n      \"VULN\",\n      \"NOT VULN\"\n    )\n  )\n\ntract_vuln_sumstats <- tracts_vuln %>% \n  group_by(pop_vuln) %>% \n  summarize(\n    tract_count = n(),\n    med_inc = median(median_incomeE, na.rm = TRUE),\n    med_pop = median(total_popE),\n    med_elderly = median(over_65E)\n  )\n\nkable(\n  tract_vuln_sumstats %>% st_drop_geometry(),\n  col.names = c(\n    \"Vulnerability\",\n    \"Tract Ct.\",\n    \"Med. Inc.\",\n    \"Med. Pop.\",\n    \"% 65+\"\n  ),\n  caption = \"Tract Demographics For PA Census Tracts By Vulnerability\",\n  format.args = list(big.mark = \",\")\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Tract Demographics For PA Census Tracts By Vulnerability\n\n|Vulnerability | Tract Ct.| Med. Inc.| Med. Pop.| % 65+|\n|:-------------|---------:|---------:|---------:|-----:|\n|NOT VULN      |     2,771|  76,535.0|     3,830|   705|\n|VULN          |       615|  39,628.5|     3,019|   459|\n|NA            |        59|        NA|         0|     0|\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- What income threshold did you choose and why?\n\nI chose to classify tracts with median incomes below \\$48,505.60 as vulnerable because that is the amount of money considered to be a \"living wage\" by the MIT living wage calculator for a single adult in Pennsylvania (https://livingwage.mit.edu/states/42). While this number is significantly higher than what many advocates push for the minimum wage to be (\\$23.32 per hour vs. \\$15 per hour), it is essentially impossible to live on either amount of money without being a single adult (i.e. families on this income are extremely vulnerable).  \n\n- What elderly population threshold did you choose and why?\n\nI chose to classify tracts with elderly population shares more than two-times the share of median elderly individuals to others in the median tract population as vulnerable.  Some fluctuation in the percent population of elderly people is expected, but having more than double the median share ensures that a tract has an unusually large concentration of this vulnerable group and can therefore be labeled vulnerable as a whole.\n\n- How many tracts meet your vulnerability criteria?\n\n615 out of 2830.\n\n- What percentage of PA census tracts are considered vulnerable by your definition?\n\n21.73145%\n\n---\n\n#### Step 4: Calculate Distance to Hospitals \n\nFor each vulnerable tract, calculate the distance to the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Transform to appropriate projected CRS\n\ntracts_vuln_proj <- st_transform(tracts_vuln, 3365) # PA South projection, measures in feet.\nhospitals_proj <- st_transform(hospitals, 3365)\n\n# Calculate distance from each tract centroid to nearest hospital\n\nhospital_access <- tracts_vuln_proj %>% \n  mutate(\n    nearest_hospital = st_nearest_feature(st_centroid(geometry), hospitals_proj),\n    hosp_dist_ft = st_distance(st_centroid(geometry), hospitals_proj[nearest_hospital, ], by_element = TRUE),\n    hosp_dist_ft = as.numeric(str_remove(hosp_dist_ft, \" [US_survey_foot]\"))\n  ) %>% \n  mutate(\n    hosp_dist_mi = hosp_dist_ft / 5280,\n    pct_eld = (over_65E / total_popE) * 100\n  )\n\nha_stats <- hospital_access %>% \n  group_by(pop_vuln) %>% \n  summarize(\n    tract_count = n(),\n    med_pop = median(total_popE),\n    pct_eld = median(pct_eld, na.rm = TRUE),\n    med_inc = median(median_incomeE, na.rm = TRUE),\n    max_hosp_dist = max(hosp_dist_mi),\n    med_hosp_dist = median(hosp_dist_mi),\n    mean_hosp_dist = mean(hosp_dist_mi),\n    min_hosp_dist = min(hosp_dist_mi),\n    over_15mi = sum(hosp_dist_mi > 15, na.rm = TRUE)\n  )\n\nkable(\n  ha_stats %>% st_drop_geometry(),\n  col.names = c(\n    \"Vulnerability\",\n    \"Tract Ct.\",\n    \"Med. Pop.\",\n    \"% 65+\",\n    \"Med. Inc.\",\n    \"Max Hosp. Dist.\",\n    \"Med. Hosp. Dist.\",\n    \"Avg. Hosp. Dist.\",\n    \"Min. Hosp. Dist.\",\n    \"Hosp > 15 Mi. Away\"\n  ),\n  caption = \"Hospital Accessibility By Distance In PA Census Tracts By Vulnerability\",\n  format.args = list(big.mark = \",\")\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Hospital Accessibility By Distance In PA Census Tracts By Vulnerability\n\n|Vulnerability | Tract Ct.| Med. Pop.|     % 65+| Med. Inc.| Max Hosp. Dist.| Med. Hosp. Dist.| Avg. Hosp. Dist.| Min. Hosp. Dist.| Hosp > 15 Mi. Away|\n|:-------------|---------:|---------:|---------:|---------:|---------------:|----------------:|----------------:|----------------:|------------------:|\n|NOT VULN      |     2,771|     3,830| 19.470235|  76,535.0|        32.84460|         3.277554|         4.853786|        0.0383749|                117|\n|VULN          |       615|     3,019| 15.935919|  39,628.5|        21.19688|         1.404611|         2.512866|        0.0209525|                 10|\n|NA            |        59|         0|  2.164759|        NA|        19.46141|         1.662165|         3.070067|        0.1656159|                  1|\n\n\n:::\n:::\n\n\n**Requirements:**\n- Use an appropriate projected coordinate system for Pennsylvania\n- Calculate distances in miles\n- Explain why you chose your projection\n\n**Questions to answer:**\n- What is the average distance to the nearest hospital for vulnerable tracts?\n\n~2.5 miles.\n\n- What is the maximum distance?\n\n~21.2 miles.\n\n- How many vulnerable tracts are more than 15 miles from the nearest hospital?\n\n10.\n\n---\n\n#### Step 5: Identify Underserved Areas \n\nDefine \"underserved\" as vulnerable tracts that are more than 15 miles from the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create underserved variable\n\nunderserved <- hospital_access %>% \n  filter(\n    pop_vuln == \"VULN\" & hosp_dist_mi > 15\n  )\n```\n:::\n\n\n**Questions to answer:**\n- How many tracts are underserved?\n\n10.\n\n- What percentage of vulnerable tracts are underserved?\n\n1.62%.\n\n- Does this surprise you? Why or why not?\n\nAt first, this surprised me.  I was shocked to see that there is such equity in PA tract hospital access (NON-vulnerable tracts have more than double the rate of being underserved at 4.22%).  However, then I looked into the data and the logic that was used for this assignment.  However, this does appear to make some sense from a healthcare point of view.  People who are in vulnerable groups (such as the elderly and the poor) tend to suffer dispraportionately from various health disorders.  Since many of them cannot afford proper treatment, they could be far sicker on average than non-vulnerable tracts (i.e. more customers forced to pay up to the private healthcare system for pricy treatments that may have been caught much earlier or be milder in wealthy, young communities; more customers = more incentive for having a hospital).\n\n---\n\n#### Step 6: Aggregate to County Level\n\nUse spatial joins and aggregation to calculate county-level statistics about vulnerable populations and hospital access.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Spatial join tracts to counties\n\ntracts_by_county <- hospital_access %>% \n  mutate(COUNTY_NAM = toupper(str_remove(NAMELSADCO, \" County\"))) %>% \n  st_drop_geometry(.) %>% \n  right_join(pa_counties %>% select(COUNTY_NAM))\n\n# Aggregate statistics by county\n\ncounty_stats <- tracts_by_county %>% \n  group_by(NAMELSADCO) %>% \n  summarize(\n    vuln_tracts = sum(pop_vuln == \"VULN\", na.rm = TRUE),\n    underserved = sum(pop_vuln == \"VULN\" & hosp_dist_mi > 15, na.rm = TRUE),\n    pct_underserved = sum(round((underserved / vuln_tracts)*100, digits = 2), na.rm = TRUE),\n    av_dist_vuln = mean(hosp_dist_mi[pop_vuln == \"VULN\"], na.rm = TRUE),\n    tot_vuln_pop = sum(total_popE[pop_vuln == \"VULN\"], na.rm = TRUE)\n  ) %>% \n  arrange(desc(pct_underserved)) %>% \n  st_drop_geometry(.)\n\nkable(\n  county_stats %>% st_drop_geometry(),\n  col.names = c(\n    \"County\",\n    \"Vuln. Tract Ct.\",\n    \"Underserved Tract Ct.\",\n    \"% Vuln. Underserved\",\n    \"Avg. Vuln. Tract Hospital Dist. (Mi)\",\n    \"Total Vuln. Pop.\"\n  ),\n  caption = \"Vulnerable Tract Hospital Access By PA County\",\n  format.args = list(big.mark = \",\")\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Vulnerable Tract Hospital Access By PA County\n\n|County                | Vuln. Tract Ct.| Underserved Tract Ct.| % Vuln. Underserved| Avg. Vuln. Tract Hospital Dist. (Mi)| Total Vuln. Pop.|\n|:---------------------|---------------:|---------------------:|-------------------:|------------------------------------:|----------------:|\n|Cameron County        |               1|                     1|              100.00|                           18.6735478|            1,988|\n|Clearfield County     |               2|                     2|              100.00|                           18.0124475|            5,388|\n|Forest County         |               2|                     2|              100.00|                           18.4029670|            6,959|\n|Monroe County         |               3|                     2|               66.67|                           11.6800270|            6,188|\n|Pike County           |               4|                     2|               50.00|                           15.1619124|            4,842|\n|Centre County         |               9|                     1|               11.11|                            4.0123526|           29,815|\n|Adams County          |               3|                     0|                0.00|                            2.1312493|           12,802|\n|Allegheny County      |              89|                     0|                0.00|                            1.9015773|          218,595|\n|Armstrong County      |               2|                     0|                0.00|                            3.8373415|            5,651|\n|Beaver County         |              12|                     0|                0.00|                            3.0150367|           33,151|\n|Bedford County        |               1|                     0|                0.00|                            3.7967562|            2,855|\n|Berks County          |              14|                     0|                0.00|                            1.5072831|           48,610|\n|Blair County          |               7|                     0|                0.00|                            1.1604791|           20,858|\n|Bradford County       |               1|                     0|                0.00|                            1.9572736|            3,270|\n|Bucks County          |               4|                     0|                0.00|                            3.5295983|           12,871|\n|Butler County         |               4|                     0|                0.00|                            2.5364948|           12,423|\n|Cambria County        |              14|                     0|                0.00|                            2.7775321|           28,834|\n|Carbon County         |               1|                     0|                0.00|                            1.7338388|            4,129|\n|Chester County        |               3|                     0|                0.00|                            6.0104386|           10,803|\n|Clarion County        |               1|                     0|                0.00|                            1.4748202|            4,205|\n|Clinton County        |               3|                     0|                0.00|                            8.5937603|           10,607|\n|Columbia County       |               4|                     0|                0.00|                            0.9158765|           18,272|\n|Crawford County       |               4|                     0|                0.00|                            4.0501543|           10,056|\n|Cumberland County     |               6|                     0|                0.00|                            6.3656400|           17,121|\n|Dauphin County        |              10|                     0|                0.00|                            1.6769353|           32,940|\n|Delaware County       |              19|                     0|                0.00|                            1.7783719|           58,843|\n|Elk County            |               0|                     0|                0.00|                                  NaN|                0|\n|Erie County           |              24|                     0|                0.00|                            2.1400735|           68,039|\n|Fayette County        |              10|                     0|                0.00|                            3.5632866|           33,334|\n|Franklin County       |               2|                     0|                0.00|                            4.2337039|            9,027|\n|Fulton County         |               0|                     0|                0.00|                                  NaN|                0|\n|Greene County         |               0|                     0|                0.00|                                  NaN|                0|\n|Huntingdon County     |               2|                     0|                0.00|                           12.1712270|            4,688|\n|Indiana County        |               5|                     0|                0.00|                            2.6964158|           15,752|\n|Jefferson County      |               4|                     0|                0.00|                            4.6638150|           10,473|\n|Juniata County        |               0|                     0|                0.00|                                  NaN|                0|\n|Lackawanna County     |              16|                     0|                0.00|                            1.3060602|           44,450|\n|Lancaster County      |              11|                     0|                0.00|                            3.0115688|           43,297|\n|Lawrence County       |               9|                     0|                0.00|                            2.6804600|           19,554|\n|Lebanon County        |               5|                     0|                0.00|                            2.3806181|           21,429|\n|Lehigh County         |              18|                     0|                0.00|                            3.2863094|           74,838|\n|Luzerne County        |              25|                     0|                0.00|                            2.2111037|           84,455|\n|Lycoming County       |               5|                     0|                0.00|                            1.1237174|           19,974|\n|McKean County         |               3|                     0|                0.00|                            2.4005371|            9,076|\n|Mercer County         |              10|                     0|                0.00|                            1.3481923|           25,022|\n|Mifflin County        |               3|                     0|                0.00|                            1.4624390|            8,522|\n|Montgomery County     |               7|                     0|                0.00|                            2.1769785|           18,927|\n|Montour County        |               0|                     0|                0.00|                                  NaN|                0|\n|Northampton County    |               9|                     0|                0.00|                            1.7245675|           38,467|\n|Northumberland County |               9|                     0|                0.00|                           10.3342036|           21,689|\n|Perry County          |               0|                     0|                0.00|                                  NaN|                0|\n|Philadelphia County   |             156|                     0|                0.00|                            1.1405039|          652,792|\n|Potter County         |               0|                     0|                0.00|                                  NaN|                0|\n|Schuylkill County     |               7|                     0|                0.00|                            3.7125959|           22,349|\n|Snyder County         |               0|                     0|                0.00|                                  NaN|                0|\n|Somerset County       |               2|                     0|                0.00|                            0.8350523|            5,715|\n|Sullivan County       |               0|                     0|                0.00|                                  NaN|                0|\n|Susquehanna County    |               0|                     0|                0.00|                                  NaN|                0|\n|Tioga County          |               0|                     0|                0.00|                                  NaN|                0|\n|Union County          |               1|                     0|                0.00|                            1.0611659|            3,378|\n|Venango County        |               3|                     0|                0.00|                            6.0349187|            5,427|\n|Warren County         |               3|                     0|                0.00|                            4.6299697|            8,032|\n|Washington County     |               8|                     0|                0.00|                            2.7769327|           16,356|\n|Wayne County          |               1|                     0|                0.00|                            0.8359027|            4,469|\n|Westmoreland County   |              18|                     0|                0.00|                            3.1229884|           37,446|\n|Wyoming County        |               0|                     0|                0.00|                                  NaN|                0|\n|York County           |              16|                     0|                0.00|                            1.2546210|           44,126|\n\n\n:::\n:::\n\n\n**Required county-level statistics:**\n- Number of vulnerable tracts\n- Number of underserved tracts  \n- Percentage of vulnerable tracts that are underserved\n- Average distance to nearest hospital for vulnerable tracts\n- Total vulnerable population\n\n**Questions to answer:**\n- Which 5 counties have the highest percentage of underserved vulnerable tracts?\n\n1. Cameron (100%)\n2. Clearfield (100%)\n3. Forest (100%)\n4. Monroe (66.67%)\n5. Pike (50%)\n\n- Which counties have the most vulnerable people living far from hospitals?\n\nAssuming the line for \"far from hospitals\" is >15 miles, there are only four counties that meet that criteria in their average distance to the nearest hospital for vulnerable tracts (sorted by vulnerable population):\n\n1. Forest (6,959 people; 18.4 mi)\n2. Clearfield (5,388 people; 18 mi)\n3. Pike County (4,842 people; 15.17 mi)\n4. Cameron (1,988 people; 18.67 mi)\n\n- Are there any patterns in where underserved counties are located?\n\nAll underserved counties appear to be quite rural with there being two major clusters: Monroe and Pike to the south east of Scranton, and Forest, Clearfield, Cameron, and Centre all clustered around the state forests in north-central PA.\n\n---\n\n#### Step 7: Create Summary Table \n\nCreate a professional table showing the top 10 priority counties for healthcare investment.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create and format priority counties table\n\npriority_counties <- county_stats %>% \n  arrange(desc(pct_underserved)) %>% \n  slice_head(n = 6) %>% #There are only 6 counties with under-served vulnerable tracts.\n  select(NAMELSADCO, pct_underserved)\n    \nkable(\n  priority_counties %>% st_drop_geometry(),\n  col.names = c(\n    \"County\",\n    \"% of Vuln. Tracts Underserved\"\n  ),\n  caption = \"Top 6 Priority Counties For Healthcare Investment\",\n  format.args = list(big.mark = \",\")\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Top 6 Priority Counties For Healthcare Investment\n\n|County            | % of Vuln. Tracts Underserved|\n|:-----------------|-----------------------------:|\n|Cameron County    |                        100.00|\n|Clearfield County |                        100.00|\n|Forest County     |                        100.00|\n|Monroe County     |                         66.67|\n|Pike County       |                         50.00|\n|Centre County     |                         11.11|\n\n\n:::\n:::\n\n\n**Requirements:**\n- Use `knitr::kable()` or similar for formatting\n- Include descriptive column names\n- Format numbers appropriately (commas for population, percentages, etc.)\n- Add an informative caption\n- Sort by priority (you decide the metric)\n\n---\n\n## Part 2: Comprehensive Visualization \n\nUsing the skills from Week 3 (Data Visualization), create publication-quality maps and charts.\n\n### Map 1: County-Level Choropleth \n\nCreate a choropleth map showing healthcare access challenges at the county level.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create county-level access map\n\ncounty_stats_merge <- tracts_by_county %>% \n  group_by(COUNTY_NAM) %>% \n  summarize(\n    vuln_tracts = sum(pop_vuln == \"VULN\", na.rm = TRUE),\n    underserved = sum(pop_vuln == \"VULN\" & hosp_dist_mi > 15, na.rm = TRUE),\n    pct_underserved = sum(round((underserved / vuln_tracts), digits = 2), na.rm = TRUE),\n    av_dist_vuln = mean(hosp_dist_mi[pop_vuln == \"VULN\"], na.rm = TRUE),\n    tot_vuln_pop = sum(total_popE[pop_vuln == \"VULN\"], na.rm = TRUE)\n  ) %>% \n  left_join(pa_counties %>% select(COUNTY_NAM)) %>% \n  st_as_sf(.)\n\nfont_add_google(\"Ubuntu\", \"ubuntu\")\nshowtext_auto()\n\nggplot(county_stats_merge) +\n  geom_sf(aes(fill = pct_underserved), color = \"black\", size = 0.3) +\n  coord_sf(clip = \"off\") +\n  scale_fill_fermenter(\n    name = \"% of Vulnerable\\nTracts Underserved\",\n    labels = percent,\n    palette = \"BuPu\",\n    breaks = classIntervals(county_stats_merge$pct_underserved, n = 3, style = \"jenks\")$brks,\n    direction = 1,\n    limits = c(0, 1)\n  ) +\n  annotation_scale(\n    location = \"bl\",\n    width_hint = 0.5,\n    pad_x = unit(2, \"cm\"),\n    pad_y = unit(-1.2, \"cm\"),\n    unit_category = \"imperial\",\n    style = \"ticks\",\n    text_family = \"ubuntu\"\n  ) +\n  annotation_north_arrow(\n    location = \"bl\",\n    pad_x = unit(0, \"cm\"),\n    pad_y = unit(-1.5, \"cm\"),\n    style = north_arrow_fancy_orienteering(text_family = \"ubuntu\")\n  ) +\n  labs(\n    title = \"PA Counties With Vulnerable Tracts Lacking Hospital Access\",\n    subtitle = \"Vulnerable Tracts Either Have Med. Inc. < $48,505.60 and/or have >35.76% 65+ Y/O Population\",\n    caption = \"Source: ACS 2018-2022\"\n  ) +\n  theme_void() +\n  theme(\n    text = element_text(family = \"ubuntu\"),\n    plot.title = element_text(\n      family = \"ubuntu\",\n      size = 16,\n      face = \"bold\",\n      margin = margin(b = 5),\n      hjust = 0.5\n    ),\n    plot.subtitle = element_text(\n      family = \"ubuntu\",\n      size = 8,\n      face = \"bold\",\n      margin = margin(b = 5),\n      hjust = 0.5\n    ),\n    plot.title.position = \"plot\",\n    plot.caption = element_text(\n      family = \"ubuntu\",\n      size = 8,\n      color = \"grey60\",\n      hjust = 1,\n      margin = margin(t = 1, unit = \"cm\")\n    ),\n    plot.caption.position = \"plot\",\n    legend.position = \"right\",\n    legend.title = element_text(\n      family = \"ubuntu\",\n      size = 10,\n      face = \"bold\",\n      hjust = 0.5,\n      margin = margin(b = 0.5, unit = \"cm\")\n    ),\n    legend.text = element_text(\n      family = \"ubuntu\",\n      size = 9,\n      hjust = 0.5\n    ),\n    plot.margin = margin(0, 20, 0, 20)\n  )\n```\n\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n**Requirements:**\n- Fill counties by percentage of vulnerable tracts that are underserved\n- Include hospital locations as points\n- Use an appropriate color scheme\n- Include clear title, subtitle, and caption\n- Use `theme_void()` or similar clean theme\n- Add a legend with formatted labels\n\n---\n\n### Map 2: Detailed Vulnerability Map \n\nCreate a map highlighting underserved vulnerable tracts.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create detailed tract-level map\n\nggplot(hospital_access) +\n  geom_sf(\n    aes(fill = pop_vuln),\n    color = \"white\",\n    size = 0.3\n  ) +\n  geom_sf(\n    data = underserved,\n    aes(fill = \"Underserved\"),\n    color = \"white\",\n    size = 0.3\n  ) +\n  geom_sf(\n    data = hospitals,\n    aes(color = \"Hospitals\"),\n    size = 1,\n    shape = 3\n  ) +\n  coord_sf(clip = \"off\") +\n  scale_fill_manual(\n    name = \"Legend\",\n    values = c(\"Underserved\" = \"#e41a1c\", \"VULN\" = \"#fb9a99\", \"NOT VULN\" = \"gray90\"),\n    labels = c(\"Underserved\" = \"Underserved\", \"VULN\" = \"Vulnerable\", \"NOT VULN\" = \"Not Vulnerable\"),\n    breaks = c(\"Underserved\", \"VULN\", \"NOT VULN\")\n  ) +\n  scale_color_manual(\n    name = \"Legend\",\n    values = c(\"Hospitals\" = \"#1f78b4\") \n  ) +\n  guides(\n    fill = guide_legend(title = NULL, byrow = TRUE),\n    color = guide_legend(title = NULL, byrow = TRUE)\n  ) +\n  annotation_scale(\n    location = \"bl\",\n    width_hint = 0.5,\n    pad_x = unit(2, \"cm\"),\n    pad_y = unit(-1.2, \"cm\"),\n    unit_category = \"imperial\",\n    style = \"ticks\",\n    text_family = \"ubuntu\"\n  ) +\n  annotation_north_arrow(\n    location = \"bl\",\n    pad_x = unit(0, \"cm\"),\n    pad_y = unit(-1.5, \"cm\"),\n    style = north_arrow_fancy_orienteering(text_family = \"ubuntu\")\n  ) +\n  labs(\n    title = \"PA Hospital Access For Vulnerable and Underserved Tracts\",\n    subtitle = \"Vulnerable Tracts Either Have Med. Inc. < $48,505.60 and/or have >35.76% 65+ Y/O Population\\nUnderserved Tracts Are Vulnerable Tracts With Centers > 15 Mi From The Closest Hospital\",\n    caption = \"Source: ACS 2018-2022\"\n  ) +\n  theme_void() +\n  theme(\n    text = element_text(family = \"ubuntu\"),\n    plot.title = element_text(\n      family = \"ubuntu\",\n      size = 16,\n      face = \"bold\",\n      margin = margin(b = 5),\n      hjust = 0.5\n    ),\n    plot.subtitle = element_text(\n      family = \"ubuntu\",\n      size = 8,\n      face = \"bold\",\n      margin = margin(b = 5),\n      hjust = 0.5\n    ),\n    plot.title.position = \"plot\",\n    plot.caption = element_text(\n      family = \"ubuntu\",\n      size = 8,\n      color = \"grey60\",\n      hjust = 1,\n      margin = margin(t = 1, unit = \"cm\")\n    ),\n    plot.caption.position = \"plot\",\n    legend.position = \"right\",\n    legend.text = element_text(\n      family = \"ubuntu\",\n      size = 9\n    ),\n    plot.margin = margin(0, 20, 0, 20)\n  )\n```\n\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n**Requirements:**\n- Show underserved vulnerable tracts in a contrasting color\n- Include county boundaries for context\n- Show hospital locations\n- Use appropriate visual hierarchy (what should stand out?)\n- Include informative title and subtitle\n\n---\n\n### Chart: Distribution Analysis\n\nCreate a visualization showing the distribution of distances to hospitals for vulnerable populations.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create distribution visualization\n\nha_vuln <- hospital_access %>% \n  filter(pop_vuln == \"VULN\")\n\nha_vuln %>% \n  ggplot(aes(x = hosp_dist_mi)) + \n  geom_histogram(bins = 30, fill = \"#fb9a99\", color = \"white\") + \n  labs(\n    title = \"Hospital Distance Distribution for Vulnerable Tracts\",\n    x = \"Distance From Tract Center To Nearest Hospital (Mi)\",\n    y = \"Count of Vulnerable Tracts\",\n    caption = \"Source: ACS 2018-2022\",\n    tag = \"The vast majority of vulnerable tracts are well served by hospitals (< 5 mi. away).\\nVery few are considered underserved (> 15 mi away).\"\n  ) +\n  theme_minimal() +\n    theme(\n    text = element_text(family = \"ubuntu\"),\n    plot.title = element_text(\n      family = \"ubuntu\",\n      size = 16,\n      face = \"bold\",\n      margin = margin(b = 5),\n      hjust = 0.5\n    ),\n    plot.title.position = \"plot\",\n    plot.caption = element_text(\n      family = \"ubuntu\",\n      size = 8,\n      color = \"grey60\",\n      hjust = 1,\n      margin = margin(t = 1, unit = \"cm\")\n    ),\n    plot.caption.position = \"plot\",\n    legend.position = \"right\",\n    legend.text = element_text(\n      family = \"ubuntu\",\n      size = 9\n    ),\n    axis.title = element_text(\n      family = \"ubuntu\",\n      face = \"bold\"\n    ),\n    axis.text = element_text(\n      family = \"ubuntu\"\n    ),\n    plot.tag = element_text(\n      family = \"ubuntu\",\n      size = 8,\n      color = \"gray60\",\n      hjust = 0,\n    ),\n    plot.tag.position = c(0, 0.03),\n    plot.margin = margin(20, 20, 5, 20)\n  )\n```\n\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n**Suggested chart types:**\n- Histogram or density plot of distances\n- Box plot comparing distances across regions\n- Bar chart of underserved tracts by county\n- Scatter plot of distance vs. vulnerable population size\n\n**Requirements:**\n- Clear axes labels with units\n- Appropriate title\n- Professional formatting\n- Brief interpretation (1-2 sentences as a caption or in text)\n\n---\n\n## Part 3: Bring Your Own Data Analysis \n\nChoose your own additional spatial dataset and conduct a supplementary analysis.\n\n### Your Analysis\n\n**Your Task:**\n\n1. **Find and load additional data**\n   - Document your data source\n   - Check and standardize the CRS\n   - Provide basic summary statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load your additional dataset\n\nats <- st_read(here(\"lab/lab_2/data/Transit_Stops_(Spring_2025)/Transit_Stops_(Spring_2025).shp\"), quiet = TRUE)\n\nats_freqbus <- ats %>% \n    filter(\n    LineAbbr %in% c(\n      \"3\", \"6\", \"17\", \"18\", \"21\", \"23\", \"33\",\n      \"45\", \"46\", \"47\", \"48\", \"51\", \"52\",\n      \"56\", \"58\", \"60\", \"63\", \"66\", \"70\",\n      \"79\", \"82\", \"108\", \"113\", \"BLVDDIR\"\n    )\n  ) %>% \n  select(\n    LineAbbr, Direction, StopId, Sequence, StopName, geometry\n  ) %>% \n  st_transform(., 3365)\n\nats_rail <- ats %>% \n  filter(\n    LineAbbr %in% c(\n      \"G1\", \"T1\", \"T2\", \"T3\",\n      \"T4\", \"T5\", \"BSL\", \"MFL\",\n      \"D1\", \"D2\", \"M1\"\n    )\n  ) %>% \n  select(\n    LineAbbr, Direction, StopId, Sequence, StopName, geometry\n  ) %>% \n  st_transform(., 3365)\n\natr <- st_read(here(\"lab/lab_2/data/Transit_Routes_(Spring_2025)/Transit_Routes_(Spring_2025).shp\"), quiet = TRUE)\n\n\natr_freqbus <- atr %>% \n  filter(\n    LineAbbr %in% c(\n      \"3\", \"6\", \"17\", \"18\", \"21\", \"23\", \"33\",\n      \"45\", \"46\", \"47\", \"48\", \"51 (L)\", \"52\",\n      \"56\", \"58\", \"60\", \"63 (G)\", \"66\", \"70\",\n      \"79\", \"82 (R)\", \"108\", \"113\", \"BLVDDIR\"\n    )\n  ) %>% \n  select(\n    LineAbbr, Mode, tpField020, tpField021, geometry\n  ) %>% \n  st_transform(., 3365)\n\natr_rail <- atr %>% \n  filter(\n    LineAbbr %in% c(\n      \"G (15)\", \"T1 (10)\", \"T2 (34)\", \"T3 (13)\",\n      \"T4 (11)\", \"T5 (36)\", \"B1\", \"B2\", \"B3\", \"L1\",\n      \"D1\", \"D2\", \"M\"\n    )\n  ) %>% \n  select(\n    LineAbbr, Mode, tpField020, tpField021, geometry\n  ) %>% \n  st_transform(., 3365)\n\nphl_county <- counties(state = \"PA\", year = 2022, progress_bar = FALSE) %>% \n  filter(NAME == \"Philadelphia\") %>% \n  st_transform(., 3365)\n\nphl_tracts <- tracts(state = \"PA\", county = \"Philadelphia\", cb = TRUE, progress_bar = FALSE)\n\nphl_race <- get_acs(\n  geography = \"tract\",\n  variables = c(\n    total_pop = \"B01003_001\",\n    white_pop = \"B03002_003\",\n    black_pop = \"B03002_004\",\n    hisp_pop = \"B03002_012\"\n  ),\n  state = \"PA\",\n  county = \"Philadelphia\",\n  year = 2022,\n  output = \"wide\"\n) %>%\n  select(\n    GEOID, total_popE, white_popE, black_popE, hisp_popE\n  ) %>% \n  mutate(\n    w_pct = round(((white_popE / total_popE) * 100), digits = 2),\n    nw_pct = round(((1-(white_popE / total_popE)) * 100), digits = 2)\n  )\n\ntracts_race <- phl_tracts %>% \n  left_join(phl_race, by = \"GEOID\") %>% \n  select(GEOID, total_popE, white_popE, black_popE, hisp_popE, w_pct, nw_pct, geometry) %>% \n  st_transform(., 3365)\n```\n:::\n\n\n**Questions to answer:**\n- What dataset did you choose and why?\n\nAll Transit Routes (Spring 2025)\n- Latest data.  Used to show places that a line goes but does not stop.\n\nAll Transit Stops (Spring 2025)\n- Latest data.  Used to show where lines stop.\n\nACS 2022 (White, Black, Hispanic, Total Population) For Philadelphia Tracts\n- For racial demographic analysis later.\n\nPhiladelphia Tracts\n- Good aerial unit for this type of analysis.\n\n- What is the data source and date?\n\nSee above\n\n- How many features does it contain?\n\natr_freqbus, 24 features (frequent SEPTA bus routes)\n\nats_freqbus, 3784 features (frequent SEPTA bus stops)\n\natr_rail, 13 features (SEPTA non-regional rail lines)\n\nats_rail, 826 features (SEPTA non-regional rail stops)\n\nphl_tracts, 408 features (Philadelphia County census tracts)\n\nphl_race, 408 features (Racial data for PHL tracts)\n\n- What CRS is it in? Did you need to transform it?\n\nAll transformed to EPSG 3365 (PA South).\n\n---\n\n2. **Pose a research question**\n\nWrite a clear research statement that your analysis will answer.\n\nHow well served are non-white majority tracts by SEPTA's most frequent and reliable bus and metro routes?\n\n---\n\n3. **Conduct spatial analysis**\n\nUse at least TWO spatial operations to answer your research question.\n\n**Required operations (choose 2+):**\n- Buffers\n- Spatial joins\n- Spatial filtering with predicates\n- Distance calculations\n- Intersections or unions\n- Point-in-polygon aggregation\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Your spatial analysis\n\n#Intersections of Tracts and Lines, Uses Buffers and Intersections\n\ntract_service <- tracts_race %>% \n  mutate(\n    r_touched = ifelse(\n      lengths(st_intersects(geometry, st_buffer(atr_rail, 30))) > 0,\n      \"Y\",\n      \"N\"\n    ),\n    b_touched = ifelse(\n      lengths(st_intersects(geometry, st_buffer(atr_freqbus, 30))) > 0,\n      \"Y\",\n      \"N\"\n    ),\n    r_served = ifelse(\n      lengths(st_intersects(geometry, ats_rail)) > 0,\n      \"Y\",\n      \"N\"\n    ),\n    b_served = ifelse(\n      lengths(st_intersects(geometry, ats_freqbus)) > 0,\n      \"Y\",\n      \"N\"\n    ),\n    underserved = case_when(\n      r_touched == \"N\" & b_touched == \"N\" & r_served == \"N\" & b_served == \"N\" ~ \"NBNR\",\n      b_touched == \"N\" & b_served == \"N\" ~ \"NB\",\n      r_touched == \"N\" & r_served == \"N\" ~ \"NR\",\n      r_touched == \"Y\" & r_served == \"N\" ~ \"RPOSS\",\n      b_touched == \"Y\" & b_served == \"N\" ~ \"BPOSS\",\n      TRUE ~ \"SERVED\"\n    ),\n    underserved_neat = case_when(\n      r_touched == \"N\" & b_touched == \"N\" & r_served == \"N\" & b_served == \"N\" ~ \"No Service\",\n      b_touched == \"N\" & b_served == \"N\" ~ \"No Buses\",\n      r_touched == \"N\" & r_served == \"N\" ~ \"No Rail\",\n      r_touched == \"Y\" & r_served == \"N\" ~ \"Rail Line Without Stop\",\n      b_touched == \"Y\" & b_served == \"N\" ~ \"Bus Line Without Stop\",\n      TRUE ~ \"Served\"\n    )\n  ) \n\n#Summarize\n\nservice_summary <- tract_service %>% \n  group_by(underserved_neat) %>% \n  summarize(\n    tract_count = n(),\n    avg_nw_pct = mean(nw_pct, na.rm = TRUE)\n  )\n\nkable(\n  service_summary %>% st_drop_geometry(),\n  col.names = c(\n    \"Service Level\",\n    \"Tract Count\",\n    \"Avg. % of Pop. Non-White\"\n  ),\n  caption = \"Philadelphia Tract Service Levels And Non-White Population Share\",\n  format.args = list(big.mark = \",\")\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Philadelphia Tract Service Levels And Non-White Population Share\n\n|Service Level          | Tract Count| Avg. % of Pop. Non-White|\n|:----------------------|-----------:|------------------------:|\n|Bus Line Without Stop  |           3|                 75.50000|\n|No Buses               |          30|                 60.22966|\n|No Rail                |         195|                 67.16210|\n|No Service             |          68|                 49.31000|\n|Rail Line Without Stop |          24|                 60.71833|\n|Served                 |          88|                 73.03774|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Visualization 1, Transit Map\n\n#Clip lines to county boundaries for visualization\n\nats_freqbus <- ats_freqbus %>% \n  mutate(in_phl = ifelse(lengths(st_within(geometry, phl_county)) > 0, \"Y\", \"N\"))\n\nats_rail <- ats_rail %>% \n  mutate(in_phl = ifelse(lengths(st_within(geometry, phl_county)) > 0, \"Y\", \"N\"))\n\natr_freqbus_phl <- st_intersection(atr_freqbus, phl_county)\n\natr_rail_phl <- st_intersection(atr_rail, phl_county)\n\nggplot() +\n  geom_sf(\n    data = atr_freqbus,\n    aes(color = \"Suburban Bus Lines\"),\n    size = 0.5\n  ) +\n  geom_sf(\n    data = atr_rail,\n    aes(color = \"Suburban Rail Lines\"),\n    size = 0.5\n  ) +\n  geom_sf(\n    data = tracts_race,\n    fill = \"gray90\",\n    color = \"white\",\n    size = 0.3\n  ) +\n  geom_sf(\n    data = atr_freqbus_phl,\n    aes(color = \"City Bus Lines\"),\n    size = 0.5\n  ) + \n  geom_sf(\n    data = atr_rail_phl,\n    aes(color = \"City Rail Lines\"),\n    size = 0.5\n  ) +\n  geom_sf(\n    data = ats_freqbus,\n    aes(\n      color = ifelse(in_phl == \"Y\", \"City Bus Stops\", \"Suburban Bus Stops\"),\n      fill = ifelse(in_phl == \"Y\", \"City Bus Stops\", \"Suburban Bus Stops\")\n    ),\n    size = 0.5,\n    shape = 21\n  ) +\n  geom_sf(\n    data = ats_rail,\n    aes(color = ifelse(in_phl == \"Y\", \"City Rail Stops\", \"Suburban Rail Stops\"),\n        fill = ifelse(in_phl == \"Y\", \"City Rail Stops\", \"Suburban Rail Stops\")\n    ),\n    size = 0.5,\n    shape = 21\n  ) +\n  geom_sf(\n    data = phl_county,\n    fill = NA,\n    color = \"black\",\n    size = 1\n  ) +\n  coord_sf(clip = \"off\") +\n  scale_color_manual(\n    name = NULL,\n    values = c(\n      \"Suburban Bus Lines\" = \"gray\",\n      \"Suburban Rail Lines\" = \"gray20\",\n      \"City Bus Lines\" = \"#1f78b4\",\n      \"City Rail Lines\" = \"#ff7f00\",\n      \"City Bus Stops\" = \"#1f78b4\",\n      \"City Rail Stops\" = \"#ff7f00\",\n      \"Suburban Bus Stops\" = \"gray\",\n      \"Suburban Rail Stops\" = \"gray20\"\n    ),\n    breaks = c(\n      \"City Bus Lines\",\n      \"City Bus Stops\",\n      \"City Rail Lines\",\n      \"City Rail Stops\",\n      \"Suburban Bus Lines\",\n      \"Suburban Bus Stops\",\n      \"Suburban Rail Lines\",\n      \"Suburban Rail Stops\"\n    )\n  ) +\n  scale_fill_manual(\n    name = NULL,\n    values = c(\n      \"City Bus Stops\" = \"gray90\",\n      \"City Rail Stops\" = \"gray90\",\n      \"Suburban Bus Stops\" = \"white\",\n      \"Suburban Rail Stops\" = \"white\"\n    ),\n    guide = \"none\"\n  ) +\n  labs(\n    title = \"Philadelphia Frequent Bus And Rail Transit Network\",\n    caption = \"Source: ACS 2018-2022, OpenDataPhilly\"\n  ) +\n  annotation_scale(\n    location = \"bl\",\n    width_hint = 0.5,\n    pad_x = unit(2, \"cm\"),\n    pad_y = unit(-1.2, \"cm\"),\n    unit_category = \"imperial\",\n    style = \"ticks\",\n    text_family = \"ubuntu\"\n  ) +\n  annotation_north_arrow(\n    location = \"bl\",\n    pad_x = unit(0, \"cm\"),\n    pad_y = unit(-1.5, \"cm\"),\n    style = north_arrow_fancy_orienteering(text_family = \"ubuntu\")\n  ) +\n  theme_void() +\n  theme(\n    text = element_text(family = \"ubuntu\"),\n    plot.title = element_text(\n      family = \"ubuntu\",\n      size = 16,\n      face = \"bold\",\n      margin = margin(b = 5),\n      hjust = 0.5\n    ),\n    plot.subtitle = element_text(\n      family = \"ubuntu\",\n      size = 8,\n      face = \"bold\",\n      margin = margin(b = 5),\n      hjust = 0.5\n    ),\n    plot.title.position = \"plot\",\n    plot.caption = element_text(\n      family = \"ubuntu\",\n      size = 8,\n      color = \"grey60\",\n      hjust = 1,\n      margin = margin(t = 1, unit = \"cm\")\n    ),\n    plot.caption.position = \"plot\",\n    legend.position = \"right\",\n    legend.text = element_text(\n      family = \"ubuntu\",\n      size = 9\n    ),\n    plot.margin = margin(20, 0, 20, 0)\n  )\n```\n\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Visualization 2: Underserved Tract Map\n\nggplot() +\n  geom_sf(\n    data = atr_freqbus,\n    aes(color = \"Suburban Bus\"),\n    size = 0.5\n  ) +\n  geom_sf(\n    data = atr_rail,\n    aes(color = \"Suburban Rail\"),\n    size = 0.5\n  ) +\n  geom_sf(\n    data = tract_service,\n    aes(fill = nw_pct),\n    color = \"white\",\n    size = 0.3\n  ) +\n  geom_sf(\n    data = atr_freqbus_phl,\n    aes(color = \"City Bus\"),\n    size = 0.5\n  ) + \n  geom_sf(\n    data = atr_rail_phl,\n    aes(color = \"City Rail\"),\n    size = 0.5\n  ) +\n  geom_sf(\n    data = phl_county,\n    fill = NA,\n    color = \"black\",\n    size = 1\n  ) +\n  coord_sf(clip = \"off\") +\n  scale_color_manual(\n    name = \"Transit Lines\",\n    values = c(\n      \"Suburban Bus\" = \"gray90\",\n      \"Suburban Rail\" = \"gray70\",\n      \"City Bus\" = \"gray30\",\n      \"City Rail\" = \"gray15\"\n    ),\n    breaks = c(\n      \"City Bus\",\n      \"City Rail\",\n      \"Suburban Bus\",\n      \"Suburban Rail\"\n    )\n  ) +\n  scale_fill_viridis_c(\n    name = \"% Non-White Pop.\",\n    labels = percent,\n    option = \"cividis\"\n  ) +\n  labs(\n    title = \"Philadelphia Frequent Bus And Rail Transit Network\\nCompared To Tracts By Non-White Population\",\n    caption = \"Source: ACS 2018-2022, OpenDataPhilly\"\n  ) +\n  annotation_scale(\n    location = \"bl\",\n    width_hint = 0.5,\n    pad_x = unit(2, \"cm\"),\n    pad_y = unit(-1.2, \"cm\"),\n    unit_category = \"imperial\",\n    style = \"ticks\",\n    text_family = \"ubuntu\"\n  ) +\n  annotation_north_arrow(\n    location = \"bl\",\n    pad_x = unit(0, \"cm\"),\n    pad_y = unit(-1.5, \"cm\"),\n    style = north_arrow_fancy_orienteering(text_family = \"ubuntu\")\n  ) +\n  theme_void() +\n  theme(\n    text = element_text(family = \"ubuntu\"),\n    plot.title = element_text(\n      family = \"ubuntu\",\n      size = 16,\n      face = \"bold\",\n      margin = margin(b = 5),\n      hjust = 0.5\n    ),\n    plot.subtitle = element_text(\n      family = \"ubuntu\",\n      size = 8,\n      face = \"bold\",\n      margin = margin(b = 5),\n      hjust = 0.5\n    ),\n    plot.title.position = \"plot\",\n    plot.caption = element_text(\n      family = \"ubuntu\",\n      size = 8,\n      color = \"grey60\",\n      hjust = 1,\n      margin = margin(t = 1, unit = \"cm\")\n    ),\n    plot.caption.position = \"plot\",\n    legend.position = \"right\",\n    legend.text = element_text(\n      family = \"ubuntu\",\n      size = 9\n    ),\n    plot.margin = margin(20, 0, 20, 0)\n  )\n```\n\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Visualization 3: Transit Deserts By Type\n\nggplot() +\n  geom_sf(\n    data = tract_service,\n    aes(\n      fill = case_when(\n        underserved == \"SERVED\" ~ \"Served\",\n        underserved == \"RPOSS\" ~ \"Rail Line Without Stop\",\n        underserved == \"NR\" ~ \"No Rail Service\",\n        underserved == \"BPOSS\" ~ \"Bus Line Without Stop\",\n        underserved == \"NB\" ~ \"No Bus Service\",\n        underserved == \"NBNR\" ~ \"No Service\"\n      )\n    ),\n    color = \"white\",\n    size = 0.3\n  ) +\n  geom_sf(\n    data = phl_county,\n    fill = NA,\n    color = \"black\",\n    size = 1\n  ) +\n  coord_sf(clip = \"off\") +\n  scale_fill_manual(\n    name = \"Service Levels\",\n    values = c(\n      \"No Service\" = \"#800026\",\n      \"No Bus Service\" = \"#e31a1c\",\n      \"No Rail Service\" = \"#fd8d3c\",\n      \"Rail Line Without Stop\" = \"#fed976\",\n      \"Bus Line Without Stop\" = \"#ffffcc\",\n      \"Served\" = \"gray90\"\n    ),\n    breaks = c(\n      \"No Service\",\n      \"No Bus Service\",\n      \"No Rail Service\",\n      \"Rail Line Without Stop\",\n      \"Bus Line Without Stop\",\n      \"Served\"\n    )\n  ) +\n  labs(\n    title = \"Philadelphia Frequent Bus And Rail Transit Network\\nService Gaps By Severity\",\n    caption = \"Source: ACS 2018-2022, OpenDataPhilly\"\n  ) +\n  annotation_scale(\n    location = \"bl\",\n    width_hint = 0.5,\n    pad_x = unit(2, \"cm\"),\n    pad_y = unit(-1.2, \"cm\"),\n    unit_category = \"imperial\",\n    style = \"ticks\",\n    text_family = \"ubuntu\"\n  ) +\n  annotation_north_arrow(\n    location = \"bl\",\n    pad_x = unit(0, \"cm\"),\n    pad_y = unit(-1.5, \"cm\"),\n    style = north_arrow_fancy_orienteering(text_family = \"ubuntu\")\n  ) +\n  theme_void() +\n  theme(\n    text = element_text(family = \"ubuntu\"),\n    plot.title = element_text(\n      family = \"ubuntu\",\n      size = 16,\n      face = \"bold\",\n      margin = margin(b = 5),\n      hjust = 0.5\n    ),\n    plot.subtitle = element_text(\n      family = \"ubuntu\",\n      size = 8,\n      face = \"bold\",\n      margin = margin(b = 5),\n      hjust = 0.5\n    ),\n    plot.title.position = \"plot\",\n    plot.caption = element_text(\n      family = \"ubuntu\",\n      size = 8,\n      color = \"grey60\",\n      hjust = 1,\n      margin = margin(t = 1, unit = \"cm\")\n    ),\n    plot.caption.position = \"plot\",\n    legend.position = \"right\",\n    legend.text = element_text(\n      family = \"ubuntu\",\n      size = 9\n    ),\n    plot.margin = margin(20, 0, 20, 0)\n  )\n```\n\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Visualization 4: Minority Tracts With No Transit Service\n\nggplot() +\n  geom_sf(\n    data = tract_service,\n    aes(\n      fill = ifelse(\n        nw_pct > 50 & underserved == \"NBNR\",\n        \"Non-White Majority Without Service\",\n        \"All Others\"\n      )\n    ),\n    color = \"white\",\n    size = 0.3\n  ) +\n  geom_sf(\n    data = phl_county,\n    fill = NA,\n    color = \"black\",\n    size = 1\n  ) +\n  coord_sf(clip = \"off\") +\n  scale_fill_manual(\n    name = \"Tracts\",\n    values = c(\n      \"Non-White Majority Without Service\" = \"#800026\",\n      \"All Others\" = \"gray90\"\n    ),\n    breaks = c(\n      \"Non-White Majority Without Service\",\n      \"All Others\"\n    )\n  ) +\n  labs(\n    title = \"Philadelphia Tracts With Non-White Majority\\nLacking Frequent Bus and Rail Transit Service\",\n    caption = \"Source: ACS 2018-2022, OpenDataPhilly\"\n  ) +\n  annotation_scale(\n    location = \"bl\",\n    width_hint = 0.5,\n    pad_x = unit(2, \"cm\"),\n    pad_y = unit(-1.2, \"cm\"),\n    unit_category = \"imperial\",\n    style = \"ticks\",\n    text_family = \"ubuntu\"\n  ) +\n  annotation_north_arrow(\n    location = \"bl\",\n    pad_x = unit(0, \"cm\"),\n    pad_y = unit(-1.5, \"cm\"),\n    style = north_arrow_fancy_orienteering(text_family = \"ubuntu\")\n  ) +\n  theme_void() +\n  theme(\n    text = element_text(family = \"ubuntu\"),\n    plot.title = element_text(\n      family = \"ubuntu\",\n      size = 16,\n      face = \"bold\",\n      margin = margin(b = 5),\n      hjust = 0.5\n    ),\n    plot.subtitle = element_text(\n      family = \"ubuntu\",\n      size = 8,\n      face = \"bold\",\n      margin = margin(b = 5),\n      hjust = 0.5\n    ),\n    plot.title.position = \"plot\",\n    plot.caption = element_text(\n      family = \"ubuntu\",\n      size = 8,\n      color = \"grey60\",\n      hjust = 1,\n      margin = margin(t = 1, unit = \"cm\")\n    ),\n    plot.caption.position = \"plot\",\n    legend.position = \"right\",\n    legend.text = element_text(\n      family = \"ubuntu\",\n      size = 9\n    ),\n    plot.margin = margin(20, 0, 20, 0)\n  )\n```\n\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n**Analysis requirements:**\n- Clear code comments explaining each step\n- Appropriate CRS transformations\n- Summary statistics or counts\n- At least one map showing your findings\n- Brief interpretation of results (3-5 sentences)\n\n**Your interpretation:**\n\nI went into this analysis thinking that Philadelphia would be more like Chicago with its transit system.  In Chicago, the mostly-white North Side has some of the best public transit in the country (featuring express/local rail service, multiple parallel lines for extra capacity, etc.).  However, Philadelphia appears to have very good coverage all over the city.  While rail coverage does not reach all portions, especially lacking in the north-west along Roosevelt Boulevard and the north-east (although this area is well served by regional rail routes), the places that the tracks and frequent buses do go tend to be the most heavily non-white tracts in the city.  There are a few very small pockets of majority non-white tracts that do not have either frequent bus or metro service, but all things considered they are quite few in number and, in most cases, are just within a short walk of a tract that is better served.  \n\nAfter summarizing the numbers, tracts with no service are only (on average) 49% non-white compared to the (on average) 73% non-white populations in served (both rail and frequent bus) tracts.  One possibility for this observed pattern (which goes against the popular theory of American urbanism which claims minority populations are dispraportionately underserved by quality public transportation), is the prevalence of legacy rail infrastructure in Philadelphia.  The Trolley routes (T1, 2, 3, 4, and 5, and G1) serve tracts that approach 100% non-white population share and provide a critical, high-capacity link to major job destinations in Center City and West Philadelphia or, in the case of the G1, other rapid transit connections to the L and Broad Street Lines.  This data showcases how much of a devastating loss it would have been to commuinties of color if Philadelphia had followed in the footsteps of nearly every other North American city and ripped up its trolley tracks.  We have already seen the consequences of funding crises on rail transit in Philly in the 1990s when several popular trolley routes (including Route 56, Route 23, and G1) were replaced with buses.  While G1 trolleys have returned, Routes 56 and 23 have not been so lucky.  Across the city their wires have been torn down and their tracks paved over, despite SEPTA's promise on the day of their suspension that the substitution with buses was merely temporary.  With this said, I think it is paramount that we continute to advocate for not just the preservation, but the improvement and expansion of these services which have been endangered by Republican state senators' refusal to fund SEPTA.\n\n## Finally - A few comments about your incorporation of feedback!\nTake a few moments to clean up your markdown document and then write a line or two or three about how you may have incorporated feedback that you recieved after your first assignment. \n\nI've hidden the setup code, erased unnecessary instructions, and formatted all of my print functions as kables.\n\n---\n\n## Submission Requirements\n\n**What to submit:**\n\n1. **Rendered HTML document posted to your course portfolio** with all code, outputs, maps, and text\n   - Use `embed-resources: true` in YAML so it's a single file\n   - All code should run without errors\n   - All maps and charts should display correctly\n2. Submit the correct and working links of your assignment on Canvas\n\n---\n\n",
    "supporting": [
      "lab2_template_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}