{
  "hash": "667cfd7cf8933b1527bfc8669d200ec1",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 4: Spatial Predictive Analysis\"\nsubtitle: \"Analyzing 311 Violations\"\nauthor: \"Parker Otto\"\ndate: today\nformat: \n  html:\n    code-fold: show\n    toc: true\n    toc-location: left\n    theme: darkly\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n\n## Assignment Overview\n\nIn this lab, you will apply the spatial predictive modeling techniques demonstrated \nin the class exercise using a different 311 service request type of your choice as the predictor variable. You will build a complete spatial predictive model, document your process, and interpret your results.\n\n### Learning Objectives\n\nBy completing this assignment, you will demonstrate your ability to:\n\n- Adapt example code to analyze a new dataset\n- Build spatial features for predictive modeling\n- Apply count regression techniques to spatial data\n- Implement spatial cross-validation\n- Interpret and communicate model results\n- Critically evaluate model performance\n\n---\n\n## Step 1: Choose Your 311 Violation Type\n\n### Getting the Data\n\nVisit the Chicago 311 Service Requests dataset:\n\n<https://data.cityofchicago.org/stories/s/311-Dataset-Changes-12-11-2018/d7nq-5g7t>\n\nBrowse the available service request types (e.g., Graffiti Removal, Pothole Repair, Street Light Out, Sanitation Code Violations, etc.) and **choose one violation type** that interests you.\n\nFor this analysis, I chose to use vacant / abandoned building 311 reports as a predictor variable for burglaries in Chicago.  I chose this to test what (if any) impact this key feature of \"broken window theory\" has on a tangible (i.e. countable) measure of crime like burglaries.  In my current understanding of the theory and its use in planning literature, \"broken window theory\" is cited more in descriptions of urban decay creating a \"bad vibe\" for the neighborhood rather than exploring its impact on quantitative outcomes like burglaries.\n\n\n::: {.cell}\n\n:::\n\n\n#### Part 1: Data Loading & Exploration\n- Load your 311 data and Chicago spatial boundaries\n- Create visualizations showing the spatial distribution of your violation type\n- Describe patterns you observe\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load police districts (used for spatial cross-validation)\npoliceDistricts <- \n  st_read(\"https://data.cityofchicago.org/api/geospatial/24zt-jpfn?method=export&format=GeoJSON\") %>%\n  st_transform('ESRI:102271') %>%\n  dplyr::select(District = dist_num)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `OGRGeoJSON' from data source \n  `https://data.cityofchicago.org/api/geospatial/24zt-jpfn?method=export&format=GeoJSON' \n  using driver `GeoJSON'\nSimple feature collection with 25 features and 2 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -87.94011 ymin: 41.64455 xmax: -87.52414 ymax: 42.02303\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\n# Load police beats (smaller administrative units)\npoliceBeats <- \n  st_read(\"https://data.cityofchicago.org/api/geospatial/n9it-hstw?method=export&format=GeoJSON\") %>%\n  st_transform('ESRI:102271') %>%\n  dplyr::select(Beat = beat_num)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `OGRGeoJSON' from data source \n  `https://data.cityofchicago.org/api/geospatial/n9it-hstw?method=export&format=GeoJSON' \n  using driver `GeoJSON'\nSimple feature collection with 277 features and 4 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -87.94011 ymin: 41.64455 xmax: -87.52414 ymax: 42.02303\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\n# Load Chicago boundary\nchicagoBoundary <- \n  st_read(\"https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/DATA/Chapter5/chicagoBoundary.geojson\") %>%\n  st_transform('ESRI:102271')\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `chicagoBoundary' from data source \n  `https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/DATA/Chapter5/chicagoBoundary.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 1 feature and 1 field\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: -87.8367 ymin: 41.64454 xmax: -87.52414 ymax: 42.02304\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"✓ Loaded spatial boundaries\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Loaded spatial boundaries\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Police districts:\", nrow(policeDistricts), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Police districts: 25 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Police beats:\", nrow(policeBeats), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Police beats: 277 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Load 311 Abandoned or Vacant Building Reports\nvac_bldgs <- read.csv(here(\"lab/lab_4/data/vac_bldgs.csv\"))\n\nvac_bldgs <- vac_bldgs %>% drop_na(LATITUDE)\n\nsf_vac_bldgs <- st_as_sf(\n  vac_bldgs,\n  coords = c(\"LONGITUDE\", \"LATITUDE\"),\n  crs = 4326\n) %>% \n  st_transform('ESRI:102271') %>% \n  mutate(\n    year = str_sub(DATE.SERVICE.REQUEST.WAS.RECEIVED, -4, -1)\n  ) %>% \n  filter(year == \"2018\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nburglaries <- st_read(\"data/burglaries.shp\") %>% \n  st_transform('ESRI:102271')\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `burglaries' from data source \n  `C:\\Users\\parke\\Documents\\GitHub\\ppaportfolio\\lab\\lab_4\\data\\burglaries.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 7482 features and 22 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 340492 ymin: 552959.6 xmax: 367153.5 ymax: 594815.1\nProjected CRS: NAD83(HARN) / Illinois East\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- ggplot(chicagoBoundary) +\n  geom_sf(\n    fill = NA,\n    color = \"black\",\n    size = 1\n  ) +\n  geom_sf(\n    data = policeDistricts,\n    fill = \"gray80\",\n    color = \"gray20\",\n    size = 0.3\n  ) +\n  geom_sf(\n    data = sf_vac_bldgs,\n    size = 0.1,\n    color = \"orange\"\n  ) +\n  labs(\n    title = \"Vacant Building Locations\"\n  ) +\n   annotation_scale(\n    location = \"bl\",\n    width_hint = 0.5,\n    pad_x = unit(-0.3, \"cm\"),\n    pad_y = unit(0, \"cm\"),\n    unit_category = \"metric\",\n    style = \"ticks\",\n  ) +\n  annotation_north_arrow(\n    location = \"bl\",\n    pad_x = unit(-2, \"cm\"),\n    pad_y = unit(-0.5, \"cm\"),\n    style = north_arrow_fancy_orienteering()\n  ) +\n  coord_sf(clip = \"off\") +\n  theme_void() +\n  theme(\n    plot.title = element_text(\n      size = 12,\n      hjust = 0.5,\n      face = \"bold\"\n    ),\n    plot.subtitle = element_text(\n      hjust = 0.5,\n      face = \"bold\"\n    ),\n    plot.margin = margin(20, -0, 20, 0)\n  )\n\np2 <- ggplot(chicagoBoundary) +\n  geom_sf(\n    fill = NA,\n    color = \"black\",\n    size = 1\n  ) +\n  geom_sf(\n    data = policeDistricts,\n    fill = \"gray80\",\n    color = \"gray20\",\n    size = 0.3\n  ) +\n  geom_density_2d_filled(\n    data = data.frame(st_coordinates(sf_vac_bldgs)),\n    aes(X, Y),\n    alpha = 0.7,\n    bins = 8\n  ) +\n  scale_fill_viridis_d(\n    option = \"plasma\",\n    direction = -1,\n    guide = \"none\"\n  ) +\n  labs(\n    title = \"Density Surface\",\n    subtitle = \"Kernel Density Estimation\",\n  ) +\n   annotation_scale(\n    location = \"bl\",\n    width_hint = 0.5,\n    pad_x = unit(-0.3, \"cm\"),\n    pad_y = unit(0, \"cm\"),\n    unit_category = \"metric\",\n    style = \"ticks\",\n  ) +\n  annotation_north_arrow(\n    location = \"bl\",\n    pad_x = unit(-2, \"cm\"),\n    pad_y = unit(-0.5, \"cm\"),\n    style = north_arrow_fancy_orienteering()\n  ) +\n  coord_sf(clip = \"off\") +\n  theme_void() +\n  theme(\n    plot.title = element_text(\n      size = 12,\n      hjust = 0.5,\n      face = \"bold\"\n    ),\n    plot.subtitle = element_text(\n      hjust = 0.5,\n      face = \"bold\"\n    ),\n    plot.margin = margin(20, -0, 20, 0)\n  )\n\nplot_spacer() + p1 + plot_spacer() + p2 +\n  plot_annotation(\n    title = \"Spatial Distribution of Vacant / Abandoned Buildings in Chicago (2018)\",\n    caption = \"Data from the Chicago Open Data Portal\",\n    tag_levels = 'A',\n    theme = theme(\n      plot.title = element_text(\n        hjust = 0.5,\n        size = 14,\n        face = \"bold\"\n      )\n    )\n  ) +\n  plot_layout(widths = c(0.1, 1, 0.1, 1))\n```\n\n::: {.cell-output-display}\n![](lab_4_files/figure-html/visuals-1.png){width=672}\n:::\n:::\n\n\n##### Part 1 Response:\n\nIn this initial step, I explored the data of vacant / abandoned buildings to see where the spatial clusters of 311 reports were in Chicago.  This exploration gives us a basic understanding of the distribution of our variables to inform our model building in later steps.\n\nThe spatial pattern of 311 reported building vacancies / abandonment in 2018 clearly shows clustering of observations on Chicago's South Side and West Side.  Both of these areas are predominantly Black and have experienced extreme disinvestment historically (post-1940 when these areas shifted demographically from white to Black).\n\n\n#### Part 2: Fishnet Grid Creation\n- Create a 500m x 500m fishnet grid\n- Aggregate your violations to grid cells\n- Visualize the count distribution\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 500m grid\n\nfishnet <- st_make_grid(\n  chicagoBoundary,\n  cellsize = 500,\n  square = TRUE\n) %>% \n  st_sf() %>% \n  mutate(uniqueID = row_number()) %>% \n  st_transform('ESRI:102271')\n\n# Keep cells intersecting Chicago\n\nfishnet <- fishnet[chicagoBoundary, ]\n\n# View basic info\ncat(\"✓ Created fishnet grid\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Created fishnet grid\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Number of cells:\", nrow(fishnet), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Number of cells: 2458 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Cell size:\", 500, \"x\", 500, \"meters\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Cell size: 500 x 500 meters\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Cell area:\", round(st_area(fishnet[1,])), \"square meters\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Cell area: 250000 square meters\n```\n\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Spatial Join\n\nvac_fishnet <- st_join(sf_vac_bldgs, fishnet, join = st_within) %>% \n  st_drop_geometry() %>% \n  group_by(uniqueID) %>% \n  summarize(countVacant = n())\n\n# Join back to fishnet\n\nfishnet <- fishnet %>% \n  left_join(vac_fishnet, by = \"uniqueID\") %>% \n  mutate(countVacant = replace_na(countVacant, 0))\n\n# Summary stats\n\ncat(\"\\nBuilding vacancy or abandonment count distribution (2018):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nBuilding vacancy or abandonment count distribution (2018):\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fishnet$countVacant)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  0.000   0.000   0.000   1.565   2.000  33.000 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nCells with no 311 reported vacancies or abandonments:\", \n    sum(fishnet$countVacant == 0), \n    \"/\", nrow(fishnet),\n    \"(\", round(100 * sum(fishnet$countVacant == 0) / nrow(fishnet), 1), \"%)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCells with no 311 reported vacancies or abandonments: 1488 / 2458 ( 60.5 %)\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Visualize aggregated counts\nggplot() +\n  geom_sf(data = fishnet, aes(fill = countVacant), color = NA) +\n  geom_sf(data = chicagoBoundary, fill = NA, color = \"white\", linewidth = 1) +\n  scale_fill_viridis_c(\n    name = \"Vacancies or Abandonments\",\n    option = \"plasma\",\n    trans = \"sqrt\",  # Square root for better visualization of skewed data\n    breaks = c(0, 1, 5, 10, 20, 40)\n  ) +\n  labs(\n    title = \"Building Vacancy or Abandonment Counts\\nBy Grid Cell\",\n    subtitle = \"500m x 500m cells, Chicago 2018\"\n  ) +\n  theme_vacbldgs()\n```\n\n::: {.cell-output-display}\n![](lab_4_files/figure-html/visualize-fishnet-1.png){width=672}\n:::\n:::\n\n##### Part 2 Response:\nIn this part, I created a 500 x 500 meter fishnet grid over the City of Chicago's boundaries to create an aerial unit for this analysis that is more consistent and objective than political boundaries (wards, police districts, community areas) or Census divisions (tracts, block groups, etc.).  After creating the grid, I joined the vacancy/abandonment data to it by recording the count of 311 observations within each cell and mapping the results.  This grid-based approach allows for us to see very small outliers (such as a sea of 0 observations followed by a single observation that is quite high, as in the area near Lake Calumet at the southern border of Chicago) that may not be visible in a KDE map.\n\n\n#### Part 3: Spatial Features\n- Calculate k-nearest neighbor features\n- Perform Local Moran's I analysis\n- Identify hot spots and cold spots\n- Create distance-to-hotspot measures\n- Join any additional contextual data if you are looking for more to do and really get into this (e.g., demographics, land use)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calc mean dist to 3 nearest reported bldgs\n\n# Get coords\nfishnet_coords <- st_coordinates(st_centroid(fishnet))\nvac_coords <- st_coordinates(sf_vac_bldgs)\n\n# Calc knn and dists\n\nnn_result <- get.knnx(vac_coords, fishnet_coords, k = 3)\n\n# add to fishnet\nfishnet <- fishnet %>% \n  mutate(\n    vac_bldgs.nn = rowMeans(nn_result$nn.dist)\n  )\n\ncat(\"✓ Calculated nearest neighbor distances\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Calculated nearest neighbor distances\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fishnet$vac_bldgs.nn)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  25.18  276.32  521.01  645.33  875.42 2833.74 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Local Moran's I Fn\ncalculate_local_morans <- function(data, variable, k = 5) {\n  \n  # Create spatial weights\n  coords <- st_coordinates(st_centroid(data))\n  neighbors <- knn2nb(knearneigh(coords, k = k))\n  weights <- nb2listw(neighbors, style = \"W\", zero.policy = TRUE)\n  \n  # Calc Local MI\n  local_moran <- localmoran(data[[variable]], weights)\n  \n  # Classify clusters\n  mean_val <- mean(data[[variable]], na.rm = TRUE)\n  \n  data %>% \n    mutate(\n      local_i = local_moran[, 1],\n      p_value = local_moran[, 5],\n      is_significant = p_value < 0.05,\n      \n      moran_class = case_when(\n        !is_significant ~ \"Not Significant\",\n        local_i > 0 & .data[[variable]] > mean_val ~ \"High-High\",\n        local_i > 0 & .data[[variable]] <= mean_val ~ \"Low-Low\",\n        local_i < 0 & .data[[variable]] > mean_val ~ \"High-Low\",\n        local_i < 0 & .data[[variable]] <= mean_val ~ \"Low-High\",\n        TRUE ~ \"Not Significant\"\n      )\n    )\n}\n\n# Apply\nfishnet <- calculate_local_morans(fishnet, \"countVacant\", k = 5)\n```\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Visualize hot spots\nggplot() +\n  geom_sf(\n    data = fishnet, \n    aes(fill = moran_class), \n    color = NA\n  ) +\n  scale_fill_manual(\n    values = c(\n      \"High-High\" = \"#d7191c\",\n      \"High-Low\" = \"#fdae61\",\n      \"Low-High\" = \"#abd9e9\",\n      \"Low-Low\" = \"#2c7bb6\",\n      \"Not Significant\" = \"gray90\"\n    ),\n    name = \"Cluster Type\"\n  ) +\n  labs(\n    title = \"Local Moran's I: Vacant or Abandoned Building Clusters\",\n    subtitle = \"High-High = Hot spots of disorder\"\n  ) +\n  theme_vacbldgs()\n```\n\n::: {.cell-output-display}\n![](lab_4_files/figure-html/visualize-morans-1.png){width=768}\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get centroids of \"High-High\" cells (hot spots)\nhotspots <- fishnet %>%\n  filter(moran_class == \"High-High\") %>%\n  st_centroid()\n\n# Calculate distance from each cell to nearest hot spot\nif (nrow(hotspots) > 0) {\n  fishnet <- fishnet %>%\n    mutate(\n      dist_to_hotspot = as.numeric(\n        st_distance(st_centroid(fishnet), hotspots %>% st_union())\n      )\n    )\n  \n  cat(\"✓ Calculated distance to vacant or abandoned building hot spots\\n\")\n  cat(\"  - Number of hot spot cells:\", nrow(hotspots), \"\\n\")\n} else {\n  fishnet <- fishnet %>%\n    mutate(dist_to_hotspot = 0)\n  cat(\"⚠ No significant hot spots found\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Calculated distance to vacant or abandoned building hot spots\n  - Number of hot spot cells: 260 \n```\n\n\n:::\n:::\n\n##### Part 3 Response:\nIn this part, I used Local Moran's I to map out clusters of spatial autocorrelation in the vacant/abandoned building reports to confirm the visual analyses done in the previous steps.  Unlike visual checks for clustering, this step permutes the data to check for cluster significance (the threshold we use here is a pseudo-p-value > 0.05).  The visualizations produced here confirm that there are significant clusters of 311 vacant/abandoned building reports on the city's South and West Sides.  Geographically, these areas are both predominantly Black and have been historically disinvested in (and continue to be disinvested in despite recent efforts from more progressive administrations).  What surprised me was that there was no significant cluster of low-low values on the North Side.  \n\nI also added a spatial variable to the fishnet dataset for use in the models later.  This was the average distance between each cell centroid and the 3 nearest observations of vacant/abandoned building 311 reports in meters.\n\n#### Part 4: Count Regression Models\n- Fit Poisson regression\n- Fit Negative Binomial regression\n- Compare model fit (AIC)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Join district information to fishnet\nfishnet <- st_join(\n  fishnet,\n  policeDistricts,\n  join = st_within,\n  left = TRUE\n) %>%\n  filter(!is.na(District))  # Remove cells outside districts\n\ncat(\"✓ Joined police districts\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Joined police districts\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Districts:\", length(unique(fishnet$District)), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Districts: 22 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Cells:\", nrow(fishnet), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Cells: 1708 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Add burglary stuff\n\nburglaries_fishnet <- st_join(burglaries, fishnet, join = st_within) %>%\n  st_drop_geometry() %>%\n  group_by(uniqueID) %>%\n  summarize(countBurglaries = n()) \n\nfishnet <- fishnet %>%\n  left_join(burglaries_fishnet, by = \"uniqueID\") %>%\n  mutate(countBurglaries = replace_na(countBurglaries, 0))\n\n#Create clean modeling dataset\nfishnet_model <- fishnet %>% \n  st_drop_geometry() %>% \n  dplyr::select(\n    uniqueID,\n    District,\n    countBurglaries,\n    countVacant,\n    vac_bldgs.nn,\n    dist_to_hotspot\n  ) %>% \n  na.omit()\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit Poisson regression\nmodel_poisson <- glm(\n  countBurglaries ~ countVacant + vac_bldgs.nn + \n    dist_to_hotspot,\n  data = fishnet_model,\n  family = \"poisson\"\n)\n\n# Summary\nsummary(model_poisson)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = countBurglaries ~ countVacant + vac_bldgs.nn + \n    dist_to_hotspot, family = \"poisson\", data = fishnet_model)\n\nCoefficients:\n                   Estimate  Std. Error z value             Pr(>|z|)    \n(Intercept)      1.85762905  0.03220422  57.683 < 0.0000000000000002 ***\ncountVacant      0.02493441  0.00340518   7.323    0.000000000000243 ***\nvac_bldgs.nn    -0.00139760  0.00006337 -22.056 < 0.0000000000000002 ***\ndist_to_hotspot -0.00001276  0.00000575  -2.220               0.0265 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for poisson family taken to be 1)\n\n    Null deviance: 6710.3  on 1707  degrees of freedom\nResidual deviance: 5003.4  on 1704  degrees of freedom\nAIC: 9071.7\n\nNumber of Fisher Scoring iterations: 6\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate dispersion parameter\ndispersion <- sum(residuals(model_poisson, type = \"pearson\")^2) / \n              model_poisson$df.residual\n\ncat(\"Dispersion parameter:\", round(dispersion, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDispersion parameter: 3.22 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Rule of thumb: >1.5 suggests overdispersion\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRule of thumb: >1.5 suggests overdispersion\n```\n\n\n:::\n\n```{.r .cell-code}\nif (dispersion > 1.5) {\n  cat(\"⚠ Overdispersion detected! Consider Negative Binomial model.\\n\")\n} else {\n  cat(\"✓ Dispersion looks okay for Poisson model.\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n⚠ Overdispersion detected! Consider Negative Binomial model.\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_nb <- glm.nb(\n  countBurglaries ~ countVacant + vac_bldgs.nn +\n    dist_to_hotspot,\n  data = fishnet_model\n)\n\nsummary(model_nb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm.nb(formula = countBurglaries ~ countVacant + vac_bldgs.nn + \n    dist_to_hotspot, data = fishnet_model, init.theta = 1.597519007, \n    link = log)\n\nCoefficients:\n                    Estimate   Std. Error z value             Pr(>|z|)    \n(Intercept)      1.896748946  0.059542163  31.856 < 0.0000000000000002 ***\ncountVacant      0.024209868  0.007662541   3.160              0.00158 ** \nvac_bldgs.nn    -0.001593618  0.000098262 -16.218 < 0.0000000000000002 ***\ndist_to_hotspot  0.000004013  0.000009570   0.419              0.67500    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for Negative Binomial(1.5975) family taken to be 1)\n\n    Null deviance: 2529.4  on 1707  degrees of freedom\nResidual deviance: 1924.1  on 1704  degrees of freedom\nAIC: 7653.5\n\nNumber of Fisher Scoring iterations: 1\n\n              Theta:  1.5975 \n          Std. Err.:  0.0927 \n\n 2 x log-likelihood:  -7643.5160 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Compare AIC (lower is better)\ncat(\"\\nModel Comparison:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nModel Comparison:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Poisson AIC:\", round(AIC(model_poisson), 1), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPoisson AIC: 9071.7 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Negative Binomial AIC:\", round(AIC(model_nb), 1), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNegative Binomial AIC: 7653.5 \n```\n\n\n:::\n:::\n\n##### Part 4 Response:\nIn this part, I use Poisson regression and Negative Binomial Regression to attempt to predict burglary counts in a given fishnet grid cell using the count of vacant/abandoned building 311 reports, the cell's centroid's distance to the nearest 311 report, and the cell's distance to the nearest 311 report hotspot (a cell labeled as having high reports and whose neighbors also have high reports) found during the Local Moran's I analysis.  I also check for overdispersion, which resulted in a value of 3.22 which (since it's greater than the rule of thumb threshold of 1.5) implies overdispersion where the variance of our crime data is greater than the mean (breaking the Poisson asumption that variance and mean are equal).  Given my knowledge of Chicago, I believe that this overdispersion may be caused by contagion effects (in many cases, burglaries are done by groups of teenagers and young adults likely to not venture far from their local area).  Given the overdispersion detected, I also fit a Negative Binomial model which allows for extra variance.  I tested both models' quality by comparing the values of the Akaike Information Criterion for both, finding the Negative Binomial model to be of better quality given its lower value (7653.5 vs. 9071.7).  \n\nThe results of the Negative Binomial model show that the count of vacant/abandoned building reports in a cell and the cell centroid's distance to the nearest vacant/abandoned building report were statistically significant predictors for the count of burglaries in a cell, while distance to a hotspot was not significant.  The interpretations of coefficients of significant predictors are as follows: (1) As the count of vacant/abandoned building 311 reports in a cell increases by 1, the predicted count of burglaries in that cell increases by 2.5248% holding all other variables constant and (2) as the average distance between a cells centroid and the 3 nearest vacant/abandoned building 311 reports increases by 1 meter, the predicted count of burglaries in that cell decreases by 0.159%.  To put the second predictor into a more appropriate scale for interpretation, I rescaled the coefficient with the following equation: exp(-0.001593618 * 1000) to get 0.2031115.  This means that as the cell's centroid's average distance to the 3 nearest neighboring vacant/abandoned building 311 reports increases by 1 kilometer, the predicted count of burglaries in that cell decreases by 79.69%.\n\n#### Part 5: Spatial Cross-Validation (2017)\n- Implement Leave-One-Group-Out cross-validation on 2017 data\n- Calculate and report error metrics (MAE, RMSE)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get unique districts\ndistricts <- unique(fishnet_model$District)\ncv_results <- tibble()\n\ncat(\"Running LOGO Cross-Validation...\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRunning LOGO Cross-Validation...\n```\n\n\n:::\n\n```{.r .cell-code}\nfor (i in seq_along(districts)) {\n  \n  test_district <- districts[i]\n  \n  # Split data\n  train_data <- fishnet_model %>% filter(District != test_district)\n  test_data <- fishnet_model %>% filter(District == test_district)\n  \n  # Fit model on training data\n  model_cv <- glm.nb(\n    countBurglaries ~ countVacant + vac_bldgs.nn + \n      dist_to_hotspot,\n    data = train_data\n  )\n  \n  # Predict on test data\n  test_data <- test_data %>%\n    mutate(\n      prediction = predict(model_cv, test_data, type = \"response\")\n    )\n  \n  # Calculate metrics\n  mae <- mean(abs(test_data$countBurglaries - test_data$prediction))\n  rmse <- sqrt(mean((test_data$countBurglaries - test_data$prediction)^2))\n  \n  # Store results\n  cv_results <- bind_rows(\n    cv_results,\n    tibble(\n      fold = i,\n      test_district = test_district,\n      n_test = nrow(test_data),\n      mae = mae,\n      rmse = rmse\n    )\n  )\n  \n  cat(\"  Fold\", i, \"/\", length(districts), \"- District\", test_district, \n      \"- MAE:\", round(mae, 2), \"\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Fold 1 / 22 - District 5 - MAE: 2.5 \n  Fold 2 / 22 - District 4 - MAE: 2.27 \n  Fold 3 / 22 - District 22 - MAE: 2.44 \n  Fold 4 / 22 - District 6 - MAE: 3.14 \n  Fold 5 / 22 - District 8 - MAE: 2.34 \n  Fold 6 / 22 - District 7 - MAE: 2.93 \n  Fold 7 / 22 - District 3 - MAE: 5.48 \n  Fold 8 / 22 - District 2 - MAE: 2.37 \n  Fold 9 / 22 - District 9 - MAE: 2.62 \n  Fold 10 / 22 - District 10 - MAE: 2.21 \n  Fold 11 / 22 - District 1 - MAE: 2.33 \n  Fold 12 / 22 - District 12 - MAE: 3.61 \n  Fold 13 / 22 - District 15 - MAE: 2.12 \n  Fold 14 / 22 - District 11 - MAE: 2.64 \n  Fold 15 / 22 - District 18 - MAE: 2.54 \n  Fold 16 / 22 - District 25 - MAE: 2.8 \n  Fold 17 / 22 - District 14 - MAE: 3.02 \n  Fold 18 / 22 - District 19 - MAE: 2.07 \n  Fold 19 / 22 - District 16 - MAE: 1.82 \n  Fold 20 / 22 - District 17 - MAE: 1.89 \n  Fold 21 / 22 - District 20 - MAE: 1.88 \n  Fold 22 / 22 - District 24 - MAE: 2.17 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Overall results\ncat(\"\\n✓ Cross-Validation Complete\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n✓ Cross-Validation Complete\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Mean MAE:\", round(mean(cv_results$mae), 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean MAE: 2.6 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Mean RMSE:\", round(mean(cv_results$rmse), 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean RMSE: 3.45 \n```\n\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Show results\ncv_results %>%\n  arrange(desc(mae)) %>%\n  kable(\n    digits = 2,\n    caption = \"LOGO CV Results by District\"\n  ) %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"margin-left: auto; margin-right: auto;\">\n<caption>LOGO CV Results by District</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:right;\"> fold </th>\n   <th style=\"text-align:left;\"> test_district </th>\n   <th style=\"text-align:right;\"> n_test </th>\n   <th style=\"text-align:right;\"> mae </th>\n   <th style=\"text-align:right;\"> rmse </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:right;\"> 7 </td>\n   <td style=\"text-align:left;\"> 3 </td>\n   <td style=\"text-align:right;\"> 43 </td>\n   <td style=\"text-align:right;\"> 5.48 </td>\n   <td style=\"text-align:right;\"> 7.25 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 12 </td>\n   <td style=\"text-align:left;\"> 12 </td>\n   <td style=\"text-align:right;\"> 73 </td>\n   <td style=\"text-align:right;\"> 3.61 </td>\n   <td style=\"text-align:right;\"> 5.12 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 4 </td>\n   <td style=\"text-align:left;\"> 6 </td>\n   <td style=\"text-align:right;\"> 63 </td>\n   <td style=\"text-align:right;\"> 3.14 </td>\n   <td style=\"text-align:right;\"> 4.20 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 17 </td>\n   <td style=\"text-align:left;\"> 14 </td>\n   <td style=\"text-align:right;\"> 46 </td>\n   <td style=\"text-align:right;\"> 3.02 </td>\n   <td style=\"text-align:right;\"> 4.42 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 6 </td>\n   <td style=\"text-align:left;\"> 7 </td>\n   <td style=\"text-align:right;\"> 52 </td>\n   <td style=\"text-align:right;\"> 2.93 </td>\n   <td style=\"text-align:right;\"> 3.64 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 16 </td>\n   <td style=\"text-align:left;\"> 25 </td>\n   <td style=\"text-align:right;\"> 85 </td>\n   <td style=\"text-align:right;\"> 2.80 </td>\n   <td style=\"text-align:right;\"> 3.95 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 14 </td>\n   <td style=\"text-align:left;\"> 11 </td>\n   <td style=\"text-align:right;\"> 43 </td>\n   <td style=\"text-align:right;\"> 2.64 </td>\n   <td style=\"text-align:right;\"> 3.27 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 9 </td>\n   <td style=\"text-align:left;\"> 9 </td>\n   <td style=\"text-align:right;\"> 107 </td>\n   <td style=\"text-align:right;\"> 2.62 </td>\n   <td style=\"text-align:right;\"> 3.07 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 15 </td>\n   <td style=\"text-align:left;\"> 18 </td>\n   <td style=\"text-align:right;\"> 30 </td>\n   <td style=\"text-align:right;\"> 2.54 </td>\n   <td style=\"text-align:right;\"> 4.30 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:left;\"> 5 </td>\n   <td style=\"text-align:right;\"> 98 </td>\n   <td style=\"text-align:right;\"> 2.50 </td>\n   <td style=\"text-align:right;\"> 2.94 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3 </td>\n   <td style=\"text-align:left;\"> 22 </td>\n   <td style=\"text-align:right;\"> 112 </td>\n   <td style=\"text-align:right;\"> 2.44 </td>\n   <td style=\"text-align:right;\"> 2.85 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 8 </td>\n   <td style=\"text-align:left;\"> 2 </td>\n   <td style=\"text-align:right;\"> 56 </td>\n   <td style=\"text-align:right;\"> 2.37 </td>\n   <td style=\"text-align:right;\"> 3.14 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 5 </td>\n   <td style=\"text-align:left;\"> 8 </td>\n   <td style=\"text-align:right;\"> 197 </td>\n   <td style=\"text-align:right;\"> 2.34 </td>\n   <td style=\"text-align:right;\"> 3.39 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 11 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:right;\"> 28 </td>\n   <td style=\"text-align:right;\"> 2.33 </td>\n   <td style=\"text-align:right;\"> 2.91 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 2 </td>\n   <td style=\"text-align:left;\"> 4 </td>\n   <td style=\"text-align:right;\"> 235 </td>\n   <td style=\"text-align:right;\"> 2.27 </td>\n   <td style=\"text-align:right;\"> 3.54 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 10 </td>\n   <td style=\"text-align:left;\"> 10 </td>\n   <td style=\"text-align:right;\"> 63 </td>\n   <td style=\"text-align:right;\"> 2.21 </td>\n   <td style=\"text-align:right;\"> 2.90 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 22 </td>\n   <td style=\"text-align:left;\"> 24 </td>\n   <td style=\"text-align:right;\"> 41 </td>\n   <td style=\"text-align:right;\"> 2.17 </td>\n   <td style=\"text-align:right;\"> 3.10 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 13 </td>\n   <td style=\"text-align:left;\"> 15 </td>\n   <td style=\"text-align:right;\"> 32 </td>\n   <td style=\"text-align:right;\"> 2.12 </td>\n   <td style=\"text-align:right;\"> 2.48 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 18 </td>\n   <td style=\"text-align:left;\"> 19 </td>\n   <td style=\"text-align:right;\"> 63 </td>\n   <td style=\"text-align:right;\"> 2.07 </td>\n   <td style=\"text-align:right;\"> 2.71 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 20 </td>\n   <td style=\"text-align:left;\"> 17 </td>\n   <td style=\"text-align:right;\"> 82 </td>\n   <td style=\"text-align:right;\"> 1.89 </td>\n   <td style=\"text-align:right;\"> 2.33 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 21 </td>\n   <td style=\"text-align:left;\"> 20 </td>\n   <td style=\"text-align:right;\"> 30 </td>\n   <td style=\"text-align:right;\"> 1.88 </td>\n   <td style=\"text-align:right;\"> 2.20 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 19 </td>\n   <td style=\"text-align:left;\"> 16 </td>\n   <td style=\"text-align:right;\"> 129 </td>\n   <td style=\"text-align:right;\"> 1.82 </td>\n   <td style=\"text-align:right;\"> 2.25 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n##### Part 5 Response:\n\nIn this part, I implemented Leave-One-Group-Out Cross Validation (LOGO-CV) and calculated the Mean Absolute Error (MAE) and Root Mean Squared Error (RMSE) to test how well the Negative Binomial model performs on new data.  Interestingly, the police districts that performed the worst in this assessment (had the highest RMSE and MAE) were Districts 3 (where the model is off on average 5.48 burglaries) and 12 (off by an average of 3.61 per cell).  Both of these districts are in active hotspots of intense gentrification.  District 3 covers the Woodlawn Community Area which is seeing rapidly intesified institutional spending for the Obama Presidential Library and expansion of the UChicago campus (particulary undergraduate housing).  Several new high-rises are actively under construction in the neighborhood and more have been built despite its significant decline between 1950 and 2010 where large swaths of its vacant (abandoned) housing was demolished (leaving many lots empty and unused to this day) along with its rapid transit line. (This neighborhood is frequently a study area in my research outside of Weitzman and a neighborhood I've worked in for 5 years).  Further, District 12 is home to the Fulton Market area which has only recently been one of the most desirable (and expensive) neighborhoods in the entire region and is now home to corporate giants like McDonalds and Google along with dozens of new skyscrapers and other urban renewal projects that came with them.  Interestingly, District 3 sees a large count of actual vacant/abandoned building 311 reports whereas District 12 sees very few.  This implies that there is some other factor impacting burglaries in these two districts than the vacancies studied here.\n\n#### Part 6: Model Evaluation\n- Compare to KDE baseline\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert burglaries to ppp (point pattern) format for spatstat\nburglaries_ppp <- as.ppp(\n  st_coordinates(burglaries),\n  W = as.owin(st_bbox(chicagoBoundary))\n)\n\n# Calculate KDE with 1km bandwidth\nkde_burglaries <- density.ppp(\n  burglaries_ppp,\n  sigma = 1000,  # 1km bandwidth\n  edge = TRUE    # Edge correction\n)\n\n# Convert to terra raster (modern approach, not raster::raster)\nkde_raster <- rast(kde_burglaries)\n\n# Extract KDE values to fishnet cells\nfishnet <- fishnet %>%\n  mutate(\n    kde_value = terra::extract(\n      kde_raster,\n      vect(fishnet),\n      fun = mean,\n      na.rm = TRUE\n    )[, 2]  # Extract just the values column\n  )\n\ncat(\"✓ Calculated KDE baseline\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Calculated KDE baseline\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot() +\n  geom_sf(data = fishnet, aes(fill = kde_value), color = NA) +\n  geom_sf(data = chicagoBoundary, fill = NA, color = \"white\", linewidth = 1) +\n  scale_fill_viridis_c(\n    name = \"KDE Value\",\n    option = \"plasma\"\n  ) +\n  labs(\n    title = \"Kernel Density Estimation Baseline\",\n    subtitle = \"Simple spatial smoothing of burglary locations\"\n  ) +\n  theme_vacbldgs()\n```\n\n::: {.cell-output-display}\n![](lab_4_files/figure-html/visualize-kde-1.png){width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit final model on all data\nfinal_model <- glm.nb(\n  countBurglaries ~ countVacant + vac_bldgs.nn + \n    dist_to_hotspot,\n  data = fishnet_model\n)\n\n# Add predictions back to fishnet\nfishnet <- fishnet %>%\n  mutate(\n    prediction_nb = predict(final_model, fishnet_model, type = \"response\")[match(uniqueID, fishnet_model$uniqueID)]\n  )\n\n# Also add KDE predictions (normalize to same scale as counts)\nkde_sum <- sum(fishnet$kde_value, na.rm = TRUE)\ncount_sum <- sum(fishnet$countBurglaries, na.rm = TRUE)\nfishnet <- fishnet %>%\n  mutate(\n    prediction_kde = (kde_value / kde_sum) * count_sum\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create three maps\np1 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = countBurglaries), color = NA) +\n  scale_fill_viridis_c(name = \"Count\", option = \"plasma\", limits = c(0, 15)) +\n  labs(title = \"Actual Burglaries\") +\n  theme_vacbldgs()\n\np2 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = prediction_nb), color = NA) +\n  scale_fill_viridis_c(name = \"Predicted\", option = \"plasma\", limits = c(0, 15)) +\n  labs(title = \"Model Predictions (Neg. Binomial)\") +\n  theme_vacbldgs()\n\np3 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = prediction_kde), color = NA) +\n  scale_fill_viridis_c(name = \"Predicted\", option = \"plasma\", limits = c(0, 15)) +\n  labs(title = \"KDE Baseline Predictions\") +\n  theme_vacbldgs()\n\np1 + p2 + p3 +\n  plot_annotation(\n    title = \"Actual vs. Predicted Burglaries\",\n    subtitle = \"Does our complex model outperform simple KDE?\"\n  )\n```\n\n::: {.cell-output-display}\n![](lab_4_files/figure-html/compare-models-1.png){width=1152}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate performance metrics\ncomparison <- fishnet %>%\n  st_drop_geometry() %>%\n  filter(!is.na(prediction_nb), !is.na(prediction_kde)) %>%\n  summarize(\n    model_mae = mean(abs(countBurglaries - prediction_nb)),\n    model_rmse = sqrt(mean((countBurglaries - prediction_nb)^2)),\n    kde_mae = mean(abs(countBurglaries - prediction_kde)),\n    kde_rmse = sqrt(mean((countBurglaries - prediction_kde)^2))\n  )\n\ncomparison %>%\n  pivot_longer(everything(), names_to = \"metric\", values_to = \"value\") %>%\n  separate(metric, into = c(\"approach\", \"metric\"), sep = \"_\") %>%\n  pivot_wider(names_from = metric, values_from = value) %>%\n  kable(\n    digits = 2,\n    caption = \"Model Performance Comparison\"\n  ) %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"margin-left: auto; margin-right: auto;\">\n<caption>Model Performance Comparison</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> approach </th>\n   <th style=\"text-align:right;\"> mae </th>\n   <th style=\"text-align:right;\"> rmse </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> model </td>\n   <td style=\"text-align:right;\"> 2.44 </td>\n   <td style=\"text-align:right;\"> 3.42 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> kde </td>\n   <td style=\"text-align:right;\"> 2.06 </td>\n   <td style=\"text-align:right;\"> 2.95 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate errors\nfishnet <- fishnet %>%\n  mutate(\n    error_nb = countBurglaries - prediction_nb,\n    error_kde = countBurglaries - prediction_kde,\n    abs_error_nb = abs(error_nb),\n    abs_error_kde = abs(error_kde)\n  )\n\n# Map errors\np1 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = error_nb), color = NA) +\n  scale_fill_gradient2(\n    name = \"Error\",\n    low = \"#2166ac\", mid = \"white\", high = \"#b2182b\",\n    midpoint = 0,\n    limits = c(-10, 10)\n  ) +\n  labs(title = \"Model Errors (Actual - Predicted)\") +\n  theme_vacbldgs()\n\np2 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = abs_error_nb), color = NA) +\n  scale_fill_viridis_c(name = \"Abs. Error\", option = \"magma\") +\n  labs(title = \"Absolute Model Errors\") +\n  theme_vacbldgs()\n\np1 + p2\n```\n\n::: {.cell-output-display}\n![](lab_4_files/figure-html/prediction-errors-1.png){width=960}\n:::\n:::\n\n##### Part 6 Response:\nIn this part, I compare the baseline Kernel Density predictions and the locations of actual burglaries to the Negative Binomial regression predictions.  Comparing the NB regression to the simple KDE predictions allows us to see whether the more complex model beats the simple baseline and whether or not the spatial features added (mean distance to 3 nearest neighbors and distance to hotspot) contribute to better model performance.  The comparison between the two models shows that the Mean Absolute Error (MAE) is higher for the NBM than the KDE (2.44 for NBM vs. 2.06 for KDE) indicating worse performance compared to the simple model.  Additionally, the Root Mean Squared Error (RMSE) is higher for the NBM than the KDE (3.42 vs 2.95).  As such, the added complexity with the NBM is not justified as it is, overall, making the prediction quality worse than the simple KDE model.  Mapping out the absolute errors show significant clusters of error in Woodlawn (District 3), the West Town (District 12) and, visually, the eastern part of District 8.  Interestingly, this model appears to have high clusters of error along very specific corridors in Chicago which, due to the way Chicago is planned where the grid system denotes land use (e.g. every 4 blocks is a retail corridor and every 8 is a major retail corridor), means we can infer some things about these error clusters.  \n\nThe cluster for Woodlawn appears to be centered along East 63rd Street and Cottage Grove Avenue.  This is the terminus station for the CTA Green Line elevated rapid transit route (since the unjust demolition of more than 1 mile of the line further east in the 1980s), the cite of a 21st-century demolished public housing complex, and only half a mile from the infamous Parkway Gardens (a.k.a \"O-Block\") housing complex (which widely claimed to be the most dangerous neighborhood in Chicago).  The errors at the intersection of 63rd / Cottage are interesting as that site is home to Woodlawn's largest 21-st century redevelopment project up to the time that this data was collected (following an equitable transit-oriented development plan around the station that is still spreading outward from this node).\n\nThe cluster for West Town is along Division Avenue (a neighborhood known as Wicker Park), which is has become a major tourist destination in the 21st century due to its large concentration of trendy restaurants.  The area is generally considered quite safe (there are often families, dog walkers, and joggers using Division and surrounding streets at all times of day) which is a stark contrast to 63rd/Cottage (which is considered a \"no-go\" zone for the predominantly white, university-aged, suburban-transplant population of neighboring Hyde Park).  \n\nFinally, the cluster in District 8 (in the Chicago Lawn neighborhood) appears clustered around Western Avenue. This is another major thoroughfare (it's a truck route, the longest street in the entire city, and the center of a new call to build a bus rapid transit line that one local alderman representing the area is pushing for).  The specific part of Chicago Lawn is divided from the West Englewood neighborhood by the CSX Intermodal Facility and the extremely wide right of way running north-south that serves it.  While the area (at least to my knowledge) is not experiencing active gentrification like Woodlawn or Wicker Park, it does appear to have a large Black population along with a lot of industrial land uses (likely due to the railyard).\n\nMore research is needed to understand what these error hotspots are exactly being caused by, but there is one very interesting thread that I can see for future research: racial boundaries.  All three of these hotspot areas see dramatic shifts in racial composition due to histories of redlining and gentrification.  Woodlawn is over 95% Black while neighboring Hyde Park is only 28% (40% white).  Wicker Park tracts are 60-90% white whereas neighboring Humboldt Park tracts are ~50% Hispanic (~30% white).  Further, tracts in Chicago Lawn around Western Avenue are as much as 90% Black whereas western tracts in the same neighborhood are 70-90% Hispanic.  While this is an interesting pattern that warrants further investigation, the racial divisions in Chicago are far more widespread (with many even more pronounced examples than these) so there are likely to be even more factors at play.\n\n## Step 3: Write Your Analysis\n\n### Critical Requirement: Explain Each Step\n\n**For each major section, you must explain in your own words:**\n\n- **What** you are doing in that step\n- **Why** this step is important for the analysis\n- **What** you found or learned from the results\n\nDo not simply copy text from the example or from your AI friend. \nThink about the purpose of each technique and articulate it in your own words.\n\n---\n\n## Step 4: Format Your Document\n\n### Formatting Requirements\n\nYour rendered HTML document should be **professional and easy to read**:\n\n#### ✓ Clean Code\n- Remove unnecessary code, comments, or debugging lines\n- Keep only essential code chunks\n- Use `code-fold: show` in your YAML header\n\n#### ✓ Clear Structure\n- Use headers to organize sections\n- Include a table of contents\n- Add your name and date\n\n#### ✓ Readable Text\n- Ensure all text renders properly (no broken markdown)\n- Check that headers appear as headers (not plain text)\n- Use proper markdown formatting\n\n#### ✓ Quality Visualizations\n- All plots should have titles and labels\n- Maps should be readable\n- Use consistent color schemes\n\n#### ✓ Professional Presentation\n- Proofread for typos\n- Remove any \"Your answer here\" placeholders\n- Make sure all code runs without errors\n- Make IT NEAT. WE GOTTA LOOK GOOD HERE.\n\n---\n\n## Submission Checklist\n\nBefore you submit, verify that your document includes:\n\n### Required Components\n\n- [ ] **Introduction**: Brief description of your chosen 311 violation type and why you selected it\n- [ ] **Data Exploration**: Maps and summary statistics of your violation data\n- [ ] **Fishnet Grid**: Successfully created and visualized grid with aggregated counts\n- [ ] **Spatial Features**: At least 2-3 spatial features calculated (k-NN, distance measures, etc.)\n- [ ] **Local Moran's I**: Spatial autocorrelation analysis with interpretation\n- [ ] **Count Regression**: Both Poisson and Negative Binomial models with comparison\n- [ ] **Spatial Cross-Validation**: LOGO CV implemented on 2017 data with reported metrics\n- [ ] **Temporal Validation**: 2018 data aggregated and tested with 2017 model(OPTIONAL.)\n- [ ] **Validation Comparison**: Comparison of spatial vs. temporal validation performance\n- [ ] **Model Comparison**: Your model vs. KDE baseline for 2018 predictions\n- [ ] **Error Analysis**: Maps and discussion of where model performs well/poorly\n- [ ] **Written Explanations**: Your own words explaining each step\n\n\n### Technical Requirements\n\n- [ ] Document knits to HTML without errors\n- [ ] Code is clean and well-organized\n- [ ] All visualizations display properly\n- [ ] Headers and formatting render correctly\n- [ ] File is named successfully posted to your website\n\n---\n\n\n",
    "supporting": [
      "lab_4_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}